import type { SelectOption } from '@/types/selectInputOptions';

const InEnglish = [
  'Abundant',
  'Abundant',
  'High',
  'Ample',
  'Frequent',
  'Full',
  'Generous',
  'Average',
  'Regular',
  'Common',
  'Typical',
  'Ordinary',
  'Occasional',
  'Low',
  'Scarce',
  'Infrequent',
  'Rare',
  'Limited',
  'Sporadic',
  'None',
  'Deficient',
  'Undetected',
  'Lacking',
  'Absent',
  'Nonexistent',
  'Unusual',
  'Lost',
  'Displaced',
  'From Elsewhere',
  'Uprooted',
  'Misplaced',
  'Forfeited',
  'Between Worlds',
  'Infected',
  'Diseased',
  'Twisted',
  'Screaming',
  'Viral',
  'Invasive',
  'Bountiful',
  'Copious',
  'Rich',
  'Numerous',
  'Moderate',
  'Fair',
  'Medium',
  'Intermittent',
  'Uncommon',
  'Sparse',
  'Empty',
  'Not Present',
  'Devoid',
  'Barren',
  'Synthetic',
] as const;

const InSpanish = [
  'Abundante',
  'Fructuoso',
  'Alto',
  'Rebosante',
  'Frecuente',
  'Lleno',
  'Generoso',
  'Medio',
  'Regular',
  'Común',
  'Típico',
  'Corriente',
  'Ocasional',
  'Bajo',
  'Escaso',
  'Poco frecuente',
  'Raro',
  'Limitado',
  'Esporádico',
  'Nulo',
  'Deficiente',
  'No detectado',
  'Carente',
  'Ausente',
  'Inexistente',
  'Inusual',
  'Perdido',
  'Desplazado',
  'De otro lugar',
  'Desarraigado',
  'Extraviado',
  'Abandonado',
  'Entre mundos',
  'Infectado',
  'Enfermo',
  'Retorcido',
  'Chillón',
  'Viral',
  'Invasivo',
  'Profuso',
  'Copioso',
  'Rico',
  'Numeroso',
  'Moderado',
  'Frugal',
  'Habitual',
  'Intermitente',
  'Atípico',
  'Exiguo',
  'Vacío',
  'Agotado',
  'Falto',
  'Seco',
  'Sintética',
] as const;

export const mappedPlanetFlora: SelectOption[] = InSpanish.map((mode, index) => ({
  label: mode,
  value: InEnglish[index],
}));
