import type { SelectOption } from '@/types/selectInputOptions';

export const PlanetDescriptors: readonly (readonly [string, string])[] = [
  ['Dead Planet', 'Planeta muerto'],
  ['Empty Planet', 'Planeta vacío'],
  ['Desolate Planet', 'Planeta desolado'],
  ['Desolate Planet', 'Planeta sin habitantes'],
  ['Lifeless Planet', 'Planeta yermo'],
  ['Forsaken Planet', 'Planeta olvidado'],
  ['Life-Incompatible Planet', 'Planeta incompatible con la vida'],
  ['Low Atmosphere Planet', 'Planeta de atmósfera baja'],
  ['Airless Planet', 'Planeta sin aire'],
  ['Abandoned Planet', 'Planeta de aspecto abandonado'],
  ['Terraforming Catastrophe', 'Catástrofe de terraformación'],
  ['Rainy Planet', 'Planeta lluvioso'],
  ['Verdant Planet', 'Planeta frondoso'],
  ['Tropical Planet', 'Planeta tropical'],
  ['Viridescent Planet', 'Planeta verdusco'],
  ['Grassy Planet', 'Planeta herboso'],
  ['Temperate Planet', 'Planeta templado'],
  ['Humid Planet', 'Planeta húmedo'],
  ['Overgrown Planet', 'Planeta abundante en flora'],
  ['Flourishing Planet', 'Planeta floreciente'],
  ['Bountiful Planet', 'Planeta abundante'],
  ['Paradise Planet', 'Planeta paradisíaco'],
  ['Shattered Planet', 'Planeta en pedazos'],
  ['Fractured Planet', 'Planeta con fracturas'],
  ['Fragmented Planet', 'Planeta en fragmentación'],
  ['Contoured Planet', 'Planeta con contornos'],
  ['Cabled Planet', 'Planeta con cableado'],
  ['Webbed Planet', 'Planeta en red'],
  ['Rattling Planet', 'Planeta traqueteante'],
  ['Spined Planet', 'Planeta vertebral'],
  ['Skeletal Planet', 'Planeta de estructura esquelética'],
  ['Finned Planet', 'Planeta de aleta'],
  ['Bladed Planet', 'Planeta de cuchilla'],
  ['Shell-Strewn Planet', 'Planeta con conchas'],
  ['Fungal Planet', 'Planeta con hongos'],
  ['Sporal Planet', 'Planeta de esporas'],
  ['Capped Planet', 'Planeta con cubierta'],
  ['Ossified Planet', 'Planeta de hueso'],
  ['Petrified Planet', 'Planeta en petrificación'],
  ['Calcified Planet', 'Planeta en calcificación'],
  ['Fissured Planet', 'Planeta con fisuras'],
  ['Breached Planet', 'Planeta con brecha'],
  ['Hexagonal Planet', 'Planeta hexagonal'],
  ['Plated Planet', 'Planeta con coraza'],
  ['Scaly Planet', 'Planeta en escamación'],
  ['Mechanical Planet', 'Planeta con mecánica'],
  ['Metallic Planet', 'Planeta de metal'],
  ['Metallurgic Planet', 'Planeta con metales'],
  ['Bubbling Planet', 'Planeta burbujeante'],
  ['Frothing Planet', 'Planeta con espuma'],
  ['Foaming Planet', 'Planeta espumante'],
  ['Columned Planet', 'Planeta con columnas'],
  ['Sharded Planet', 'Planeta en fragmentos'],
  ['Pillared Planet', 'Planeta en pilares'],
  ['Planet of Light', 'Planeta de luz'],
  ['Crimson Planet', 'Planeta carmesí'],
  ['Malfunctioning Planet', 'Planeta disfuncional'],
  ['Breached Planet', 'Planeta con brecha'],
  ['Infected Planet', 'Planeta infectado'],
  ['[REDACTED] Planet', 'Planeta [EDITADO]'],
  ['Glassy Planet', 'Planeta vidrioso'],
  ['Thirsty Planet', 'Planeta sediento'],
  ['Doomed Planet', 'Planeta condenado'],
  ['Erased Planet', 'Planeta exterminado'],
  ['Temporary Planet', 'Planeta temporal'],
  ['Corrupted Planet', 'Planeta corrompido'],
  ['Planetary Anomaly', 'Anomalía planetaria'],
  ['Charred Planet', 'Planeta carbonizado'],
  ['Arid Planet', 'Planeta árido'],
  ['Scorched Planet', 'Planeta abrasado'],
  ['Hot Planet', 'Planeta caluroso'],
  ['Fiery Planet', 'Planeta tórrido'],
  ['Boiling Planet', 'Planeta sofocante'],
  ['High Temperature Planet', 'Planeta de altas temperaturas'],
  ['Torrid Planet', 'Planeta caliente'],
  ['Incandescent Planet', 'Planeta incandescente'],
  ['Scalding Planet', 'Planeta hirviente'],
  ['Frozen Planet', 'Planeta congelado'],
  ['Icebound Planet', 'Planeta escarchado'],
  ['Arctic Planet', 'Planeta ártico'],
  ['Glacial Planet', 'Planeta glacial'],
  ['Sub-zero Planet', 'Planeta subcero'],
  ['Icy Planet', 'Planeta algente'],
  ['Frostbound Planet', 'Planeta con escarcha'],
  ['Freezing Planet', 'Planeta inclemente'],
  ['Hiemal Planet', 'Planeta hiemal'],
  ['Hyperborean Planet', 'Planeta septentrional'],
  ['Irradiated Planet', 'Planeta irradiado'],
  ['Radioactive Planet', 'Planeta radiactivo'],
  ['Contaminated Planet', 'Planeta contaminado'],
  ['Nuclear Planet', 'Planeta nuclear'],
  ['Isotopic Planet', 'Planeta molecular'],
  ['Decaying Nuclear Planet', 'Planeta nuclear decadente'],
  ['Gamma-Intensive Planet', 'Planeta de intensidad gamma'],
  ['High Radio Source Planet', 'Planeta de alta radiación'],
  ['Supercritical Planet', 'Planeta bullente'],
  ['High Energy Planet', 'Planeta de gran energía'],
  ['Toxic Planet', 'Planeta tóxico'],
  ['Poisonous Planet', 'Planeta venenoso'],
  ['Noxious Planet', 'Planeta nocivo'],
  ['Corrosive Planet', 'Planeta corrosivo'],
  ['Acidic Planet', 'Planeta de clima ácido'],
  ['Caustic Planet', 'Planeta ardiente'],
  ['Acrid Planet', 'Planeta acre'],
  ['Blighted Planet', 'Planeta en ruinas'],
  ['Blighted Planet', 'Planeta en la ruina'],
  ['Miasmatic Planet', 'Planeta emanante'],
  ['Rotting Planet', 'Planeta débil'],
  ['Barren Planet', 'Planeta estéril'],
  ['Desert Planet', 'Planeta desierto'],
  ['Rocky Planet', 'Planeta rocoso'],
  ['Bleak Planet', 'Planeta inhóspito'],
  ['Parched Planet', 'Planeta reseco'],
  ['Abandoned Planet', 'Planeta de aspecto abandonado'],
  ['Dusty Planet', 'Planeta con mucho polvo'],
  ['Desolate Planet', 'Planeta desolado'],
  ['Wind-swept Planet', 'Planeta de vientos salvajes'],
  ['Marshy Planet', 'Planeta marismeño'],
  ['Swamp Planet', 'Planeta pantanoso'],
  ['Tropical Planet', 'Planeta tropical'],
  ['Foggy Planet', 'Planeta neblinoso'],
  ['Misty Planet', 'Planeta brumoso'],
  ['Boggy Planet', 'Planeta cenagoso'],
  ['Quagmire Planet', 'Planeta fangoso'],
  ['Hazy Planet', 'Planeta borroso'],
  ['Cloudy Planet', 'Planeta nublado'],
  ['Vapour Planet', 'Planeta vaporoso'],
  ['Reeking Planet', 'Planeta apestoso'],
  ['Murky Planet', 'Planeta turbio'],
  ['Damp Planet', 'Planeta húmedo'],
  ['Endless Morass', 'Cenagal infinito'],
  ['Lava Planet', 'Planeta lávico'],
  ['Magma Planet', 'Planeta magmático'],
  ['Erupting Planet', 'Planeta en erupción'],
  ['Volcanic Planet', 'Planeta volcánico'],
  ['Ash-Shrouded Planet', 'Planeta envuelto en ceniza'],
  ['Ashen Planet', 'Planeta cenizo'],
  ['Tectonic Planet', 'Planeta tectónico'],
  ['Unstable Planet', 'Planeta inestable'],
  ['Violent Planet', 'Planeta violento'],
  ['Molten Planet', 'Planeta derretido'],
  ['Flame-Ruptured Planet', 'Planeta quebrado por las llamas'],
  ['Basalt Planet', 'Planeta basáltico'],
  ['Imminent Core Detonation', 'Detonación del núcleo inminente'],
  ['Obsidian Bead', 'Goteo de obsidiana'],
  ['Lost Red Planet', 'Planeta rojo perdido'],
  ['Chromatic Fog Planet', 'Planeta niebla cromática'],
  ['Scarlet Planet', 'Planeta escarlata'],
  ['Blood Planet', 'Planeta sangre'],
  ['Wine Dark Planet', 'Planeta vino tinto'],
  ['Lost Green Planet', 'Planeta verde perdido'],
  ['Doomed Jade Planet', 'Planeta jade maldito'],
  ['Haunted Emeril Planet', 'Planeta emerilio encantado'],
  ['Lost Blue Planet', 'Planeta azul perdido'],
  ['Azure Planet', 'Planeta azul celeste'],
  ['Cerulean Planet', 'Planeta azul cerúleo'],
  ['Ultramarine Planet', 'Planeta ultramarino'],
  ['Stellar Corruption Detected', 'Corrupción estelar detectada'],
  ['Vermillion Globe', 'Globo bermellón'],
  ['Vile Anomaly', 'Anomalía malvada'],
  ['Toxic Anomaly', 'Anomalía tóxica'],
  ['Deathly Green Anomaly', 'Anomalía mortal verde'],
  ['Harsh Blue Globe', 'Globo azul chillón'],
  ['Frozen Anomaly', 'Anomalía helada'],
  ['Drowning Planet', 'Planeta ahogado'],
  ['Oceanic Planet', 'Planeta oceánico'],
  ['Tidal Planet', 'Planeta de mareas'],
  ['Waterlocked Planet', 'Planeta anegado'],
  ['Aquatic Planet', 'Planeta acuático'],
  ['Marine Planet', 'Planeta marino'],
  ['Waterworld', 'Mundo acuático'],
  ['Endless Seas', 'Mares infinito'],
  ['Infested Planet', 'Planeta infestado'],
  ['Worm-ridden Planet', 'Planeta infestado de gusanos'],
  ['Tainted Planet', 'Planeta contaminado'],
  ['Mutated Planet', 'Planeta mutado'],
  ['Corrupted Planet', 'Planeta corrompido'],
  ['Infested Paradise', 'Paraíso infestado'],
  ['Toxic Horror', 'Horror tóxico'],
  ['Boiling Doom', 'Destrucción hirviente'],
  ['Radioactive Abomination', 'Abominación radioactiva'],
  ['Icy Abhorrence', 'Aberración gélida'],
  ['Xeno-Colony', 'Xenocolonia'],
  ['Caustic Nightmare', 'Pesadilla cáustica'],
  ['Fiery Dreadworld', 'Mundo terrorífico fogoso'],
  ['Frozen Hell', 'Infierno congelado'],
  ['Infected Dustbowl', 'Tierra desértica infectada'],
  ['The Nest', 'El nido'],
  ['Terrorsphere', 'Terrorfera'],
  ['Abandoned Paradise', 'Paraíso abandonado'],
  ['Overgrown Planet', 'Planeta abundante en flora'],
  ['Overgrown Relic', 'Reliquia consumida por la espesura'],
  ['The Reliquary', 'El relicario'],
  ['Abandoned Planet', 'Planeta de aspecto abandonado'],
  ['Bleached Ruin', 'Ruina blanqueada'],
  ['Decaying Ruin', 'Ruina en declive'],
  ['Ruined Planet', 'Planeta en ruinas'],
  ['Scorched Relic', 'Reliquia abrasada'],
  ['Lost to Fire', 'Perdido por el fuego'],
  ['Abandoned Crucible', 'Crisol abandonado'],
  ['Ruined Planet', 'Planeta en ruinas'],
  ['Claimed by Decay', 'Consumido por el deterioro'],
  ['Mutating Relic', 'Reliquia mutante'],
  ['Abandoned Planet', 'Planeta de aspecto abandonado'],
  ['Icy Ruin', 'Ruina helada'],
  ['Frozen Relic', 'Reliquia congelada'],
  ['Abandoned Planet', 'Planeta de aspecto abandonado'],
  ['Ruined Planet', 'Planeta arruinado'],
  ['Ruined Dustbowl', 'Polvareda en ruinas'],
  ['Abandoned Desert', 'Desierto abandonado'],
  ['Abandoned Planet', 'Planeta de aspecto abandonado'],
] as const;

export const MoonDescriptors: readonly (readonly [string, string])[] = [
  ['Dead Moon', 'Luna muerto'],
  ['Empty Moon', 'Luna vacío'],
  ['Desolate Moon', 'Luna desolado'],
  ['Lifeless Moon', 'Luna sin habitantes'],
  ['Forsaken Moon', 'Luna yermo'],
  ['Life-Incompatible Moon', 'Luna olvidado'],
  ['Low Atmosphere Moon', 'Luna incompatible con la vida'],
  ['Airless Moon', 'Luna de atmósfera baja'],
  ['Abandoned Moon', 'Luna sin aire'],
  ['Terraforming Catastrophe Moon', 'Luna de aspecto abandonado'],
  ['Rainy Moon', 'Catástrofe de terraformación'],
  ['Verdant Moon', 'Luna lluvioso'],
  ['Tropical Moon', 'Luna frondoso'],
  ['Viridescent Moon', 'Luna tropical'],
  ['Grassy Moon', 'Luna verdusco'],
  ['Temperate Moon', 'Luna herboso'],
  ['Humid Moon', 'Luna templado'],
  ['Overgrown Moon', 'Luna húmedo'],
  ['Flourishing Moon', 'Luna abundante en flora'],
  ['Bountiful Moon', 'Luna floreciente'],
  ['Paradise Moon', 'Luna abundante'],
  ['Shattered Moon', 'Luna paradisíaco'],
  ['Fractured Moon', 'Luna en pedazos'],
  ['Fragmented Moon', 'Luna con fracturas'],
  ['Contoured Moon', 'Luna en fragmentación'],
  ['Cabled Moon', 'Luna con contornos'],
  ['Webbed Moon', 'Luna con cableado'],
  ['Rattling Moon', 'Luna en red'],
  ['Spined Moon', 'Luna traqueteante'],
  ['Skeletal Moon', 'Luna vertebral'],
  ['Finned Moon', 'Luna de estructura esquelética'],
  ['Bladed Moon', 'Luna de aleta'],
  ['Shell-Strewn Moon', 'Luna de cuchilla'],
  ['Fungal Moon', 'Luna con conchas'],
  ['Sporal Moon', 'Luna con hongos'],
  ['Capped Moon', 'Luna de esporas'],
  ['Ossified Moon', 'Luna con cubierta'],
  ['Petrified Moon', 'Luna de hueso'],
  ['Calcified Moon', 'Luna en petrificación'],
  ['Fissured Moon', 'Luna en calcificación'],
  ['Breached Moon', 'Luna con fisuras'],
  ['Hexagonal Moon', 'Luna con brecha'],
  ['Plated Moon', 'Luna hexagonal'],
  ['Scaly Moon', 'Luna con coraza'],
  ['Mechanical Moon', 'Luna en escamación'],
  ['Metallic Moon', 'Luna con mecánica'],
  ['Metallurgic Moon', 'Luna de metal'],
  ['Bubbling Moon', 'Luna con metales'],
  ['Frothing Moon', 'Luna burbujeante'],
  ['Foaming Moon', 'Luna con espuma'],
  ['Columned Moon', 'Luna espumante'],
  ['Sharded Moon', 'Luna con columnas'],
  ['Pillared Moon', 'Luna en fragmentos'],
  ['Moon of Light', 'Luna en pilares'],
  ['Crimson Moon', 'Luna de luz'],
  ['Malfunctioning Moon', 'Luna carmesí'],
  ['Breached Moon', 'Luna disfuncional'],
  ['Infected Moon', 'Luna con brecha'],
  ['[REDACTED] Moon', 'Luna infectado'],
  ['Glassy Moon', 'Luna [EDITADO]'],
  ['Thirsty Moon', 'Luna vidrioso'],
  ['Doomed Moon', 'Luna sediento'],
  ['Erased Moon', 'Luna condenado'],
  ['Temporary Moon', 'Luna exterminado'],
  ['Corrupted Moon', 'Luna temporal'],
  ['Moon Anomaly', 'Luna corrompido'],
  ['Charred Moon', 'Anomalía planetaria'],
  ['Arid Moon', 'Luna carbonizado'],
  ['Scorched Moon', 'Luna árido'],
  ['Hot Moon', 'Luna abrasado'],
  ['Fiery Moon', 'Luna caluroso'],
  ['Boiling Moon', 'Luna tórrido'],
  ['High Temperature Moon', 'Luna sofocante'],
  ['Torrid Moon', 'Luna de altas temperaturas'],
  ['Incandescent Moon', 'Luna caliente'],
  ['Scalding Moon', 'Luna incandescente'],
  ['Frozen Moon', 'Luna hirviente'],
  ['Icebound Moon', 'Luna congelado'],
  ['Arctic Moon', 'Luna escarchado'],
  ['Glacial Moon', 'Luna ártico'],
  ['Sub-zero Moon', 'Luna glacial'],
  ['Icy Moon', 'Luna subcero'],
  ['Frostbound Moon', 'Luna algente'],
  ['Freezing Moon', 'Luna con escarcha'],
  ['Hiemal Moon', 'Luna inclemente'],
  ['Hyperborean Moon', 'Luna hiemal'],
  ['Irradiated Moon', 'Luna septentrional'],
  ['Radioactive Moon', 'Luna irradiado'],
  ['Contaminated Moon', 'Luna radiactivo'],
  ['Nuclear Moon', 'Luna contaminado'],
  ['Isotopic Moon', 'Luna nuclear'],
  ['Decaying Nuclear Moon', 'Luna molecular'],
  ['Gamma-Intensive Moon', 'Luna nuclear decadente'],
  ['High Radio Source Moon', 'Luna de intensidad gamma'],
  ['Supercritical Moon', 'Luna de alta radiación'],
  ['High Energy Moon', 'Luna bullente'],
  ['Toxic Moon', 'Luna de gran energía'],
  ['Poisonous Moon', 'Luna tóxico'],
  ['Noxious Moon', 'Luna venenoso'],
  ['Corrosive Moon', 'Luna nocivo'],
  ['Acidic Moon', 'Luna corrosivo'],
  ['Caustic Moon', 'Luna de clima ácido'],
  ['Acrid Moon', 'Luna ardiente'],
  ['Blighted Moon', 'Luna acre'],
  ['Blighted Moon', 'Luna en ruinas'],
  ['Miasmatic Moon', 'Luna en la ruina'],
  ['Rotting Moon', 'Luna emanante'],
  ['Barren Moon', 'Luna débil'],
  ['Desert Moon', 'Luna estéril'],
  ['Rocky Moon', 'Luna desierto'],
  ['Bleak Moon', 'Luna rocoso'],
  ['Parched Moon', 'Luna inhóspito'],
  ['Abandoned Moon', 'Luna reseco'],
  ['Dusty Moon', 'Luna de aspecto abandonado'],
  ['Desolate Moon', 'Luna con mucho polvo'],
  ['Wind-swept Moon', 'Luna desolado'],
  ['Marshy Moon', 'Luna de vientos salvajes'],
  ['Swamp Moon', 'Luna marismeño'],
  ['Tropical Moon', 'Luna pantanoso'],
  ['Foggy Moon', 'Luna tropical'],
  ['Misty Moon', 'Luna neblinoso'],
  ['Boggy Moon', 'Luna brumoso'],
  ['Quagmire Moon', 'Luna cenagoso'],
  ['Hazy Moon', 'Luna fangoso'],
  ['Cloudy Moon', 'Luna borroso'],
  ['Vapour Moon', 'Luna nublado'],
  ['Reeking Moon', 'Luna vaporoso'],
  ['Murky Moon', 'Luna apestoso'],
  ['Damp Moon', 'Luna turbio'],
  ['Endless Morass', 'Luna húmedo'],
  ['Lava Moon', 'Cenagal infinito'],
  ['Magma Moon', 'Luna lávico'],
  ['Erupting Moon', 'Luna magmático'],
  ['Volcanic Moon', 'Luna en erupción'],
  ['Ash-Shrouded Moon', 'Luna volcánico'],
  ['Ashen Moon', 'Luna envuelto en ceniza'],
  ['Tectonic Moon', 'Luna cenizo'],
  ['Unstable Moon', 'Luna tectónico'],
  ['Violent Moon', 'Luna inestable'],
  ['Molten Moon', 'Luna violento'],
  ['Flame-Ruptured Moon', 'Luna derretido'],
  ['Basalt Moon', 'Luna quebrado por las llamas'],
  ['Imminent Core Detonation', 'Luna basáltico'],
  ['Obsidian Bead', 'Detonación del núcleo inminente'],
  ['Lost Red Moon', 'Goteo de obsidiana'],
  ['Chromatic Fog Moon', 'Luna rojo perdido'],
  ['Scarlet Moon', 'Luna niebla cromática'],
  ['Blood Moon', 'Luna escarlata'],
  ['Wine Dark Moon', 'Luna sangre'],
  ['Lost Green Moon', 'Luna vino tinto'],
  ['Doomed Jade Moon', 'Luna verde perdido'],
  ['Haunted Emeril Moon', 'Luna jade maldito'],
  ['Lost Blue Moon', 'Luna emerilio encantado'],
  ['Azure Moon', 'Luna azul perdido'],
  ['Cerulean Moon', 'Luna azul celeste'],
  ['Ultramarine Moon', 'Luna azul cerúleo'],
  ['Stellar Corruption Detected', 'Luna ultramarino'],
  ['Vermillion Globe', 'Corrupción estelar detectada'],
  ['Vile Anomaly', 'Globo bermellón'],
  ['Toxic Anomaly', 'Anomalía malvada'],
  ['Deathly Green Anomaly', 'Anomalía tóxica'],
  ['Harsh Blue Globe', 'Anomalía mortal verde'],
  ['Frozen Anomaly', 'Globo azul chillón'],
  ['Drowning Moon', 'Anomalía helada'],
  ['Oceanic Moon', 'Luna ahogado'],
  ['Tidal Moon', 'Luna oceánico'],
  ['Waterlocked Moon', 'Luna de mareas'],
  ['Aquatic Moon', 'Luna anegado'],
  ['Marine Moon', 'Luna acuático'],
  ['Waterworld', 'Luna marino'],
  ['Endless Seas', 'Mundo acuático'],
  ['Infested Moon', 'Mares infinito'],
  ['Worm-ridden Moon', 'Luna infestado'],
  ['Tainted Moon', 'Luna infestado de gusanos'],
  ['Mutated Moon', 'Luna contaminado'],
  ['Corrupted Moon', 'Luna mutado'],
  ['Infested Paradise', 'Luna corrompido'],
  ['Toxic Horror', 'Paraíso infestado'],
  ['Boiling Doom', 'Horror tóxico'],
  ['Radioactive Abomination', 'Destrucción hirviente'],
  ['Icy Abhorrence', 'Abominación radioactiva'],
  ['Xeno-Colony', 'Aberración gélida'],
  ['Caustic Nightmare', 'Xenocolonia'],
  ['Fiery Dreadworld', 'Pesadilla cáustica'],
  ['Frozen Hell', 'Mundo terrorífico fogoso'],
  ['Infected Dustbowl', 'Infierno congelado'],
  ['The Nest', 'Tierra desértica infectada'],
  ['Terrorsphere', 'El nido'],
  ['Abandoned Paradise', 'Terrorfera'],
  ['Overgrown Moon', 'Paraíso abandonado'],
  ['Overgrown Relic', 'Luna abundante en flora'],
  ['The Reliquary', 'Reliquia consumida por la espesura'],
  ['Abandoned Moon', 'El relicario'],
  ['Bleached Ruin', 'Luna de aspecto abandonado'],
  ['Decaying Ruin', 'Ruina blanqueada'],
  ['Ruined Moon', 'Ruina en declive'],
  ['Scorched Relic', 'Luna en ruinas'],
  ['Lost to Fire', 'Reliquia abrasada'],
  ['Abandoned Crucible', 'Perdido por el fuego'],
  ['Ruined Moon', 'Crisol abandonado'],
  ['Claimed by Decay', 'Luna en ruinas'],
  ['Mutating Relic', 'Consumido por el deterioro'],
  ['Abandoned Moon', 'Reliquia mutante'],
  ['Icy Ruin', 'Luna de aspecto abandonado'],
  ['Frozen Relic', 'Ruina helada'],
  ['Abandoned Moon', 'Reliquia congelada'],
  ['Ruined Moon', 'Luna de aspecto abandonado'],
  ['Ruined Dustbowl', 'Luna arruinado'],
  ['Abandoned Desert', 'Polvareda en ruinas'],
  ['Abandoned Moon', 'Desierto abandonado'],
] as const;

export const GiantDescriptors: readonly (readonly [string, string])[] = [
  ['Dead Giant', 'Gigante muerto'],
  ['Empty Giant', 'Gigante vacío'],
  ['Desolate Giant', 'Gigante desolado'],
  ['Lifeless Giant', 'Gigante sin habitantes'],
  ['Forsaken Giant', 'Gigante yermo'],
  ['Life-Incompatible Giant', 'Gigante olvidado'],
  ['Low Atmosphere Giant', 'Gigante incompatible con la vida'],
  ['Airless Giant', 'Gigante de atmósfera baja'],
  ['Abandoned Giant', 'Gigante sin aire'],
  ['Terraforming Catastrophe', 'Gigante de aspecto abandonado'],
  ['Rainy Giant', 'Catástrofe de terraformación'],
  ['Verdant Giant', 'Gigante lluvioso'],
  ['Tropical Giant', 'Gigante frondoso'],
  ['Viridescent Giant', 'Gigante tropical'],
  ['Grassy Giant', 'Gigante verdusco'],
  ['Temperate Giant', 'Gigante herboso'],
  ['Humid Giant', 'Gigante templado'],
  ['Overgrown Giant', 'Gigante húmedo'],
  ['Flourishing Giant', 'Gigante abundante en flora'],
  ['Bountiful Giant', 'Gigante floreciente'],
  ['Paradise Giant', 'Gigante abundante'],
  ['Shattered Giant', 'Colosal paradisíaco'],
  ['Fractured Giant', 'Gigante en pedazos'],
  ['Fragmented Giant', 'Gigante con fracturas'],
  ['Contoured Giant', 'Gigante en fragmentación'],
  ['Cabled Giant', 'Gigante con contornos'],
  ['Webbed Giant', 'Gigante con cableado'],
  ['Rattling Giant', 'Gigante en red'],
  ['Spined Giant', 'Gigante traqueteante'],
  ['Skeletal Giant', 'Gigante vertebral'],
  ['Finned Giant', 'Gigante de estructura esquelética'],
  ['Bladed Giant', 'Gigante de aleta'],
  ['Shell-Strewn Giant', 'Gigante de cuchilla'],
  ['Fungal Giant', 'Gigante con conchas'],
  ['Sporal Giant', 'Gigante con hongos'],
  ['Capped Giant', 'Gigante de esporas'],
  ['Ossified Giant', 'Gigante con cubierta'],
  ['Petrified Giant', 'Gigante de hueso'],
  ['Calcified Giant', 'Gigante en petrificación'],
  ['Fissured Giant', 'Gigante en calcificación'],
  ['Breached Giant', 'Gigante con fisuras'],
  ['Hexagonal Giant', 'Gigante con brecha'],
  ['Plated Giant', 'Gigante hexagonal'],
  ['Scaly Giant', 'Gigante con coraza'],
  ['Mechanical Giant', 'Gigante en escamación'],
  ['Metallic Giant', 'Gigante con mecánica'],
  ['Metallurgic Giant', 'Gigante de metal'],
  ['Bubbling Giant', 'Gigante con metales'],
  ['Frothing Giant', 'Gigante burbujeante'],
  ['Foaming Giant', 'Gigante con espuma'],
  ['Columned Giant', 'Gigante espumante'],
  ['Sharded Giant', 'Gigante con columnas'],
  ['Pillared Giant', 'Gigante en fragmentos'],
  ['Giant of Light', 'Gigante en pilares'],
  ['Crimson Giant', 'Gigante de luz'],
  ['Malfunctioning Giant', 'Gigante carmesí'],
  ['Breached Giant', 'Gigante disfuncional'],
  ['Infected Giant', 'Gigante con brecha'],
  ['[REDACTED] Giant', 'Gigante infectado'],
  ['Glassy Giant', 'Gigante [EDITADO]'],
  ['Thirsty Giant', 'Gigante vidrioso'],
  ['Doomed Giant', 'Gigante sediento'],
  ['Erased Giant', 'Gigante condenado'],
  ['Temporary Giant', 'Gigante exterminado'],
  ['Corrupted Giant', 'Gigante temporal'],
  ['Planetary Anomaly', 'Gigante corrompido'],
  ['Charred Giant', 'Anomalía planetaria'],
  ['Arid Giant', 'Gigante carbonizado'],
  ['Scorched Giant', 'Gigante árido'],
  ['Hot Giant', 'Gigante abrasado'],
  ['Fiery Giant', 'Gigante caluroso'],
  ['Boiling Giant', 'Gigante tórrido'],
  ['High Temperature Giant', 'Gigante sofocante'],
  ['Torrid Giant', 'Gigante de altas temperaturas'],
  ['Incandescent Giant', 'Gigante caliente'],
  ['Scalding Giant', 'Gigante incandescente'],
  ['Frozen Giant', 'Gigante hirviente'],
  ['Icebound Giant', 'Gigante congelado'],
  ['Arctic Giant', 'Gigante escarchado'],
  ['Glacial Giant', 'Gigante ártico'],
  ['Sub-zero Giant', 'Gigante glacial'],
  ['Icy Giant', 'Gigante subcero'],
  ['Frostbound Giant', 'Gigante algente'],
  ['Freezing Giant', 'Gigante con escarcha'],
  ['Hiemal Giant', 'Gigante inclemente'],
  ['Hyperborean Giant', 'Gigante hiemal'],
  ['Irradiated Giant', 'Gigante septentrional'],
  ['Radioactive Giant', 'Gigante irradiado'],
  ['Contaminated Giant', 'Gigante radiactivo'],
  ['Nuclear Giant', 'Gigante contaminado'],
  ['Isotopic Giant', 'Gigante nuclear'],
  ['Decaying Nuclear Giant', 'Gigante molecular'],
  ['Gamma-Intensive Giant', 'Gigante nuclear decadente'],
  ['High Radio Source Giant', 'Gigante de intensidad gamma'],
  ['Supercritical Giant', 'Gigante de alta radiación'],
  ['High Energy Giant', 'Gigante bullente'],
  ['Toxic Giant', 'Gigante de gran energía'],
  ['Poisonous Giant', 'Gigante tóxico'],
  ['Noxious Giant', 'Gigante venenoso'],
  ['Corrosive Giant', 'Gigante nocivo'],
  ['Acidic Giant', 'Gigante corrosivo'],
  ['Caustic Giant', 'Gigante de clima ácido'],
  ['Acrid Giant', 'Gigante ardiente'],
  ['Blighted Giant', 'Gigante acre'],
  ['Blighted Giant', 'Gigante en ruinas'],
  ['Miasmatic Giant', 'Gigante emanante'],
  ['Rotting Giant', 'Gigante débil'],
  ['Barren Giant', 'Gigante estéril'],
  ['Desert Giant', 'Gigante desierto'],
  ['Rocky Giant', 'Gigante rocoso'],
  ['Bleak Giant', 'Gigante inhóspito'],
  ['Parched Giant', 'Gigante reseco'],
  ['Abandoned Giant', 'Gigante de aspecto abandonado'],
  ['Dusty Giant', 'Gigante con mucho polvo'],
  ['Desolate Giant', 'Gigante desolado'],
  ['Wind-swept Giant', 'Gigante de vientos salvajes'],
  ['Marshy Giant', 'Gigante marismeño'],
  ['Swamp Giant', 'Gigante pantanoso'],
  ['Tropical Giant', 'Gigante tropical'],
  ['Foggy Giant', 'Gigante neblinoso'],
  ['Misty Giant', 'Gigante brumoso'],
  ['Boggy Giant', 'Gigante cenagoso'],
  ['Quagmire Giant', 'Gigante fangoso'],
  ['Hazy Giant', 'Gigante borroso'],
  ['Cloudy Giant', 'Gigante nublado'],
  ['Vapour Giant', 'Gigante vaporoso'],
  ['Reeking Giant', 'Gigante apestoso'],
  ['Murky Giant', 'Gigante turbio'],
  ['Damp Giant', 'Gigante húmedo'],
  ['Endless Morass', 'Cenagal infinito'],
  ['Lava Giant', 'Gigante lávico'],
  ['Magma Giant', 'Gigante magmático'],
  ['Erupting Giant', 'Gigante en erupción'],
  ['Volcanic Giant', 'Gigante volcánico'],
  ['Ash-Shrouded Giant', 'Gigante envuelto en ceniza'],
  ['Ashen Giant', 'Gigante cenizo'],
  ['Tectonic Giant', 'Gigante tectónico'],
  ['Unstable Giant', 'Gigante inestable'],
  ['Violent Giant', 'Gigante violento'],
  ['Molten Giant', 'Gigante derretido'],
  ['Flame-Ruptured Giant', 'Gigante quebrado por las llamas'],
  ['Basalt Giant', 'Gigante basáltico'],
  ['Imminent Core Detonation', 'Detonación del núcleo inminente'],
  ['Obsidian Bead', 'Goteo de obsidiana'],
  ['Lost Red Giant', 'Gigante rojo perdido'],
  ['Chromatic Fog Giant', 'Gigante niebla cromática'],
  ['Scarlet Giant', 'Gigante escarlata'],
  ['Blood Giant', 'Gigante sangre'],
  ['Wine Dark Giant', 'Gigante vino tinto'],
  ['Lost Green Giant', 'Gigante verde perdido'],
  ['Doomed Jade Giant', 'Gigante jade maldito'],
  ['Haunted Emeril Giant', 'Gigante emerilio encantado'],
  ['Lost Blue Giant', 'Gigante azul perdido'],
  ['Azure Giant', 'Gigante azul celeste'],
  ['Cerulean Giant', 'Gigante azul cerúleo'],
  ['Ultramarine Giant', 'Gigante ultramarino'],
  ['Stellar Corruption Detected', 'Corrupción estelar detectada'],
  ['Vermillion Globe', 'Globo bermellón'],
  ['Vile Anomaly', 'Anomalía malvada'],
  ['Toxic Anomaly', 'Anomalía tóxica'],
  ['Deathly Green Anomaly', 'Anomalía mortal verde'],
  ['Harsh Blue Globe', 'Globo azul chillón'],
  ['Frozen Anomaly', 'Anomalía helada'],
  ['Drowning Giant', 'Gigante ahogado'],
  ['Oceanic Giant', 'Gigante oceánico'],
  ['Tidal Giant', 'Gigante de mareas'],
  ['Waterlocked Giant', 'Gigante anegado'],
  ['Aquatic Giant', 'Gigante acuático'],
  ['Marine Giant', 'Gigante marino'],
  ['Waterworld', 'Mundo acuático'],
  ['Endless Seas', 'Mares infinito'],
  ['Infested Giant', 'Gigante infestado'],
  ['Worm-ridden Giant', 'Gigante infestado de gusanos'],
  ['Tainted Giant', 'Gigante contaminado'],
  ['Mutated Giant', 'Gigante mutado'],
  ['Corrupted Giant', 'Gigante corrompido'],
  ['Infested Paradise', 'Paraíso infestado'],
  ['Toxic Horror', 'Horror tóxico'],
  ['Boiling Doom', 'Destrucción hirviente'],
  ['Radioactive Abomination', 'Abominación radioactiva'],
  ['Icy Abhorrence', 'Aberración gélida'],
  ['Xeno-Colony', 'Xenocolonia'],
  ['Caustic Nightmare', 'Pesadilla cáustica'],
  ['Fiery Dreadworld', 'Mundo terrorífico fogoso'],
  ['Frozen Hell', 'Infierno congelado'],
  ['Infected Dustbowl', 'Tierra desértica infectada'],
  ['The Nest', 'El nido'],
  ['Terrorsphere', 'Terrorfera'],
  ['Abandoned Paradise', 'Paraíso abandonado'],
  ['Overgrown Gigant', 'Gigante abundante en flora'],
  ['Overgrown Relic', 'Reliquia consumida por la espesura'],
  ['The Reliquary', 'El relicario'],
  ['Abandoned Gigant', 'Gigante de aspecto abandonado'],
  ['Bleached Ruin', 'Ruina blanqueada'],
  ['Decaying Ruin', 'Ruina en declive'],
  ['Ruined Gigant', 'Gigante en ruinas'],
  ['Scorched Relic', 'Gigante en la ruina'],
  ['Lost to Fire', 'Reliquia abrasada'],
  ['Abandoned Crucible', 'Perdido por el fuego'],
  ['Ruined Gigant', 'Crisol abandonado'],
  ['Claimed by Decay', 'Gigante en ruinas'],
  ['Mutating Relic', 'Consumido por el deterioro'],
  ['Abandoned Gigant', 'Reliquia mutante'],
  ['Icy Ruin', 'Gigante de aspecto abandonado'],
  ['Frozen Relic', 'Ruina helada'],
  ['Abandoned Gigant', 'Reliquia congelada'],
  ['Ruined Gigant', 'Gigante de aspecto abandonado'],
  ['Ruined Dustbowl', 'Gigante arruinado'],
  ['Abandoned Desert', 'Polvareda en ruinas'],
  ['Abandoned Gigant', 'Desierto abandonado'],
] as const;

export const mappedPlanetDescriptors: SelectOption[] = PlanetDescriptors.map(([value, label]) => ({
  label,
  value,
}));

export const mappedMoonDescriptors: SelectOption[] = MoonDescriptors.map(([value, label]) => ({
  label,
  value,
}));

export const mappedGiantDescriptors: SelectOption[] = GiantDescriptors.map(([value, label]) => ({
  label,
  value,
}));
