import type { SelectOption } from '@/types/selectInputOptions';

export const PlanetFauna: readonly (readonly [string, string])[] = [
  ['', ''],
  ['Abundant', 'Abundante'],
  ['Abundant', 'Fructuoso'],
  ['High', 'Alto'],
  ['Ample', 'Rebosante'],
  ['Frequent', 'Frecuente'],
  ['Full', 'Lleno'],
  ['Generous', 'Generoso'],
  ['Average', 'Medio'],
  ['Regular', 'Regular'],
  ['Common', 'Común'],
  ['Typical', 'Típico'],
  ['Ordinary', 'Corriente'],
  ['Occasional', 'Ocasional'],
  ['Low', 'Bajo'],
  ['Scarce', 'Escaso'],
  ['Infrequent', 'Poco frecuente'],
  ['Rare', 'Raro'],
  ['Limited', 'Limitado'],
  ['Sporadic', 'Esporádico'],
  ['None', 'Nulo'],
  ['Deficient', 'Deficiente'],
  ['Undetected', 'No detectado'],
  ['Lacking', 'Carente'],
  ['Absent', 'Ausente'],
  ['Nonexistent', 'Inexistente'],
  ['Unusual', 'Inusual'],
  ['Lost', 'Perdido'],
  ['Displaced', 'Desplazado'],
  ['From Elsewhere', 'De otro lugar'],
  ['Uprooted', 'Desarraigado'],
  ['Misplaced', 'Extraviado'],
  ['Forfeited', 'Abandonado'],
  ['Between Worlds', 'Entre mundos'],
  ['Infected', 'Infectado'],
  ['Diseased', 'Enfermo'],
  ['Twisted', 'Retorcido'],
  ['Screaming', 'Chillón'],
  ['Viral', 'Viral'],
  ['Invasive', 'Invasivo'],
  ['Bountiful', 'Profuso'],
  ['Copious', 'Copioso'],
  ['Rich', 'Rico'],
  ['Numerous', 'Numeroso'],
  ['Moderate', 'Moderado'],
  ['Fair', 'Frugal'],
  ['Medium', 'Habitual'],
  ['Intermittent', 'Intermitente'],
  ['Uncommon', 'Atípico'],
  ['Sparse', 'Disperso'],
  ['Empty', 'Vacío'],
  ['Not Present', 'Agotado'],
  ['Devoid', 'Falto'],
  ['Barren', 'Seco'],
  ['Synthetic', 'Sintética'],
] as const;

export const mappedPlanetFauna: SelectOption[] = PlanetFauna.map(
  ([value, label]) => ({
    label,
    value,
  })
);
