import type { SelectOption } from '@/types/selectInputOptions';

const InEnglish = [
  'Dead Planet',
  'Empty Planet',
  'Desolate Planet',
  'Desolate Planet',
  'Lifeless Planet',
  'Forsaken Planet',
  'Life-Incompatible Planet',
  'Low Atmosphere Planet',
  'Airless Planet',
  'Abandoned Planet',
  'Terraforming Catastrophe',
  'Rainy Planet',
  'Verdant Planet',
  'Tropical Planet',
  'Viridescent Planet',
  'Grassy Planet',
  'Temperate Planet',
  'Humid Planet',
  'Overgrown Planet',
  'Flourishing Planet',
  'Bountiful Planet',
  'Paradise Planet',
  'Shattered Planet',
  'Fractured Planet',
  'Fragmented Planet',
  'Contoured Planet',
  'Cabled Planet',
  'Webbed Planet',
  'Rattling Planet',
  'Spined Planet',
  'Skeletal Planet',
  'Finned Planet',
  'Bladed Planet',
  'Shell-Strewn Planet',
  'Fungal Planet',
  'Sporal Planet',
  'Capped Planet',
  'Ossified Planet',
  'Petrified Planet',
  'Calcified Planet',
  'Fissured Planet',
  'Breached Planet',
  'Hexagonal Planet',
  'Plated Planet',
  'Scaly Planet',
  'Mechanical Planet',
  'Metallic Planet',
  'Metallurgic Planet',
  'Bubbling Planet',
  'Frothing Planet',
  'Foaming Planet',
  'Columned Planet',
  'Sharded Planet',
  'Pillared Planet',
  'Planet of Light',
  'Crimson Planet',
  'Malfunctioning Planet',
  'Breached Planet',
  'Infected Planet',
  '[REDACTED] Planet',
  'Glassy Planet',
  'Thirsty Planet',
  'Doomed Planet',
  'Erased Planet',
  'Temporary Planet',
  'Corrupted Planet',
  'Planetary Anomaly',
  'Charred Planet',
  'Arid Planet',
  'Scorched Planet',
  'Hot Planet',
  'Fiery Planet',
  'Boiling Planet',
  'High Temperature Planet',
  'Torrid Planet',
  'Incandescent Planet',
  'Scalding Planet',
  'Frozen Planet',
  'Icebound Planet',
  'Arctic Planet',
  'Glacial Planet',
  'Sub-zero Planet',
  'Icy Planet',
  'Frostbound Planet',
  'Freezing Planet',
  'Hiemal Planet',
  'Hyperborean Planet',
  'Irradiated Planet',
  'Radioactive Planet',
  'Contaminated Planet',
  'Nuclear Planet',
  'Isotopic Planet',
  'Decaying Nuclear Planet',
  'Gamma-Intensive Planet',
  'High Radio Source Planet',
  'Supercritical Planet',
  'High Energy Planet',
  'Toxic Planet',
  'Poisonous Planet',
  'Noxious Planet',
  'Corrosive Planet',
  'Acidic Planet',
  'Caustic Planet',
  'Acrid Planet',
  'Blighted Planet',
  'Miasmatic Planet',
  'Rotting Planet',
  'Barren Planet',
  'Desert Planet',
  'Rocky Planet',
  'Bleak Planet',
  'Parched Planet',
  'Abandoned Planet',
  'Dusty Planet',
  'Desolate Planet',
  'Wind-swept Planet',
  'Marshy Planet',
  'Swamp Planet',
  'Tropical Planet',
  'Foggy Planet',
  'Misty Planet',
  'Boggy Planet',
  'Quagmire Planet',
  'Hazy Planet',
  'Cloudy Planet',
  'Vapour Planet',
  'Reeking Planet',
  'Murky Planet',
  'Damp Planet',
  'Endless Morass',
  'Lava Planet',
  'Magma Planet',
  'Erupting Planet',
  'Volcanic Planet',
  'Ash-Shrouded Planet',
  'Ashen Planet',
  'Tectonic Planet',
  'Unstable Planet',
  'Violent Planet',
  'Molten Planet',
  'Flame-Ruptured Planet',
  'Basalt Planet',
  'Imminent Core Detonation',
  'Obsidian Bead',
  'Lost Red Planet',
  'Chromatic Fog Planet',
  'Scarlet Planet',
  'Blood Planet',
  'Wine Dark Planet',
  'Lost Green Planet',
  'Doomed Jade Planet',
  'Haunted Emeril Planet',
  'Lost Blue Planet',
  'Azure Planet',
  'Cerulean Planet',
  'Ultramarine Planet',
  'Stellar Corruption Detected',
  'Vermillion Globe',
  'Vile Anomaly',
  'Toxic Anomaly',
  'Deathly Green Anomaly',
  'Harsh Blue Globe',
  'Frozen Anomaly',
  'Drowning Planet',
  'Oceanic Planet',
  'Tidal Planet',
  'Waterlocked Planet',
  'Aquatic Planet',
  'Marine Planet',
  'Waterworld',
  'Endless Seas',
  'Infested Planet',
  'Worm-ridden Planet',
  'Tainted Planet',
  'Mutated Planet',
  'Corrupted Planet',
  'Infested Paradise',
  'Toxic Horror',
  'Boiling Doom',
  'Radioactive Abomination',
  'Icy Abhorrence',
  'Xeno-Colony',
  'Caustic Nightmare',
  'Fiery Dreadworld',
  'Frozen Hell',
  'Infected Dustbowl',
  'The Nest',
  'Terrorsphere',
  'Abandoned Paradise',
  'Overgrown Planet',
  'Overgrown Relic',
  'The Reliquary',
  'Abandoned Planet',
  'Bleached Ruin',
  'Decaying Ruin',
  'Ruined Planet',
  'Scorched Relic',
  'Lost to Fire',
  'Abandoned Crucible',
  'Ruined Planet',
  'Claimed by Decay',
  'Mutating Relic',
  'Abandoned Planet',
  'Icy Ruin',
  'Frozen Relic',
  'Abandoned Planet',
  'Ruined Planet',
  'Ruined Dustbowl',
  'Abandoned Desert',
  'Abandoned Planet',
] as const;

const InSpanish = [
  'Planeta muerto',
  'Planeta vacío',
  'Planeta desolado',
  'Planeta sin habitantes',
  'Planeta yermo',
  'Planeta olvidado',
  'Planeta incompatible con la vida',
  'Planeta de atmósfera baja',
  'Planeta sin aire',
  'Planeta de aspecto abandonado',
  'Catástrofe de terraformación',
  'Planeta lluvioso',
  'Planeta frondoso',
  'Planeta tropical',
  'Planeta verdusco',
  'Planeta herboso',
  'Planeta templado',
  'Planeta húmedo',
  'Planeta abundante en flora',
  'Planeta floreciente',
  'Planeta abundante',
  'Planeta paradisíaco',
  'Planeta en pedazos',
  'Planeta con fracturas',
  'Planeta en fragmentación',
  'Planeta con contornos',
  'Planeta con cableado',
  'Planeta en red',
  'Planeta traqueteante',
  'Planeta vertebral',
  'Planeta de estructura esquelética',
  'Planeta de aleta',
  'Planeta de cuchilla',
  'Planeta con conchas',
  'Planeta con hongos',
  'Planeta de esporas',
  'Planeta con cubierta',
  'Planeta de hueso',
  'Planeta en petrificación',
  'Planeta en calcificación',
  'Planeta con fisuras',
  'Planeta con brecha',
  'Planeta hexagonal',
  'Planeta con coraza',
  'Planeta en escamación',
  'Planeta con mecánica',
  'Planeta de metal',
  'Planeta con metales',
  'Planeta burbujeante',
  'Planeta con espuma',
  'Planeta espumante',
  'Planeta con columnas',
  'Planeta en fragmentos',
  'Planeta en pilares',
  'Planeta de luz',
  'Planeta carmesí',
  'Planeta disfuncional',
  'Planeta con brecha',
  'Planeta infectado',
  'Planeta [EDITADO]',
  'Planeta vidrioso',
  'Planeta sediento',
  'Planeta condenado',
  'Planeta exterminado',
  'Planeta temporal',
  'Planeta corrompido',
  'Anomalía planetaria',
  'Planeta carbonizado',
  'Planeta árido',
  'Planeta abrasado',
  'Planeta caluroso',
  'Planeta tórrido',
  'Planeta sofocante',
  'Planeta de altas temperaturas',
  'Planeta caliente',
  'Planeta incandescente',
  'Planeta hirviente',
  'Planeta congelado',
  'Planeta escarchado',
  'Planeta ártico',
  'Planeta glacial',
  'Planeta subcero',
  'Planeta algente',
  'Planeta con escarcha',
  'Planeta inclemente',
  'Planeta hiemal',
  'Planeta septentrional',
  'Planeta irradiado',
  'Planeta radiactivo',
  'Planeta contaminado',
  'Planeta nuclear',
  'Planeta molecular',
  'Planeta nuclear decadente',
  'Planeta de intensidad gamma',
  'Planeta de alta radiación',
  'Planeta bullente',
  'Planeta de gran energía',
  'Planeta tóxico',
  'Planeta venenoso',
  'Planeta nocivo',
  'Planeta corrosivo',
  'Planeta de clima ácido',
  'Planeta ardiente',
  'Planeta acre',
  'Planeta en ruinas',
  'Planeta emanante',
  'Planeta débil',
  'Planeta estéril',
  'Planeta desierto',
  'Planeta rocoso',
  'Planeta inhóspito',
  'Planeta reseco',
  'Planeta de aspecto abandonado',
  'Planeta con mucho polvo',
  'Planeta desolado',
  'Planeta de vientos salvajes',
  'Planeta marismeño',
  'Planeta pantanoso',
  'Planeta tropical',
  'Planeta neblinoso',
  'Planeta brumoso',
  'Planeta cenagoso',
  'Planeta fangoso',
  'Planeta borroso',
  'Planeta nublado',
  'Planeta vaporoso',
  'Planeta apestoso',
  'Planeta turbio',
  'Planeta húmedo',
  'Cenagal infinito',
  'Planeta lávico',
  'Planeta magmático',
  'Planeta en erupción',
  'Planeta volcánico',
  'Planeta envuelto en ceniza',
  'Planeta cenizo',
  'Planeta tectónico',
  'Planeta inestable',
  'Planeta violento',
  'Planeta derretido',
  'Planeta quebrado por las llamas',
  'Planeta basáltico',
  'Detonación del núcleo inminente',
  'Goteo de obsidiana',
  'Planeta rojo perdido',
  'Planeta niebla cromática',
  'Planeta escarlata',
  'Planeta sangre',
  'Planeta vino tinto',
  'Planeta verde perdido',
  'Planeta jade maldito',
  'Planeta emerilio encantado',
  'Planeta azul perdido',
  'Planeta azul celeste',
  'Planeta azul cerúleo',
  'Planeta ultramarino',
  'Corrupción estelar detectada',
  'Globo bermellón',
  'Anomalía malvada',
  'Anomalía tóxica',
  'Anomalía mortal verde',
  'Globo azul chillón',
  'Anomalía helada',
  'Planeta ahogado',
  'Planeta oceánico',
  'Planeta de mareas',
  'Planeta anegado',
  'Planeta acuático',
  'Planeta marino',
  'Mundo acuático',
  'Mares infinito',
  'Planeta infestado',
  'Planeta infestado de gusanos',
  'Planeta contaminado',
  'Planeta mutado',
  'Planeta corrompido',
  'Paraíso infestado',
  'Horror tóxico',
  'Destrucción hirviente',
  'Abominación radioactiva',
  'Aberración gélida',
  'Xenocolonia',
  'Pesadilla cáustica',
  'Mundo terrorífico fogoso',
  'Infierno congelado',
  'Tierra desértica infectada',
  'El nido',
  'Terrorfera',
  'Paraíso abandonado',
  'Planeta abundante en flora',
  'Reliquia consumida por la espesura',
  'El relicario',
  'Planeta de aspecto abandonado',
  'Ruina blanqueada',
  'Ruina en declive',
  'Planeta en ruinas',
  'Reliquia abrasada',
  'Perdido por el fuego',
  'Crisol abandonado',
  'Planeta en ruinas',
  'Consumido por el deterioro',
  'Reliquia mutante',
  'Planeta de aspecto abandonado',
  'Ruina helada',
  'Reliquia congelada',
  'Planeta de aspecto abandonado',
  'Planeta arruinado',
  'Polvareda en ruinas',
  'Desierto abandonado',
  'Planeta de aspecto abandonado',
] as const;

export const mappedPlanetDescriptors: SelectOption[] = InSpanish.map((mode, index) => ({
  label: mode,
  value: InEnglish[index],
}));

const InEnglishMoon = [
  'Dead Moon',
  'Empty Moon',
  'Desolate Moon',
  'Lifeless Moon',
  'Forsaken Moon',
  'Life-Incompatible Moon',
  'Low Atmosphere Moon',
  'Airless Moon',
  'Abandoned Moon',
  'Terraforming Catastrophe Moon',
  'Rainy Moon',
  'Verdant Moon',
  'Tropical Moon',
  'Viridescent Moon',
  'Grassy Moon',
  'Temperate Moon',
  'Humid Moon',
  'Overgrown Moon',
  'Flourishing Moon',
  'Bountiful Moon',
  'Paradise Moon',
  'Shattered Moon',
  'Fractured Moon',
  'Fragmented Moon',
  'Contoured Moon',
  'Cabled Moon',
  'Webbed Moon',
  'Rattling Moon',
  'Spined Moon',
  'Skeletal Moon',
  'Finned Moon',
  'Bladed Moon',
  'Shell-Strewn Moon',
  'Fungal Moon',
  'Sporal Moon',
  'Capped Moon',
  'Ossified Moon',
  'Petrified Moon',
  'Calcified Moon',
  'Fissured Moon',
  'Breached Moon',
  'Hexagonal Moon',
  'Plated Moon',
  'Scaly Moon',
  'Mechanical Moon',
  'Metallic Moon',
  'Metallurgic Moon',
  'Bubbling Moon',
  'Frothing Moon',
  'Foaming Moon',
  'Columned Moon',
  'Sharded Moon',
  'Pillared Moon',
  'Moon of Light',
  'Crimson Moon',
  'Malfunctioning Moon',
  'Breached Moon',
  'Infected Moon',
  '[REDACTED] Moon',
  'Glassy Moon',
  'Thirsty Moon',
  'Doomed Moon',
  'Erased Moon',
  'Temporary Moon',
  'Corrupted Moon',
  'Moon Anomaly',
  'Charred Moon',
  'Arid Moon',
  'Scorched Moon',
  'Hot Moon',
  'Fiery Moon',
  'Boiling Moon',
  'High Temperature Moon',
  'Torrid Moon',
  'Incandescent Moon',
  'Scalding Moon',
  'Frozen Moon',
  'Icebound Moon',
  'Arctic Moon',
  'Glacial Moon',
  'Sub-zero Moon',
  'Icy Moon',
  'Frostbound Moon',
  'Freezing Moon',
  'Hiemal Moon',
  'Hyperborean Moon',
  'Irradiated Moon',
  'Radioactive Moon',
  'Contaminated Moon',
  'Nuclear Moon',
  'Isotopic Moon',
  'Decaying Nuclear Moon',
  'Gamma-Intensive Moon',
  'High Radio Source Moon',
  'Supercritical Moon',
  'High Energy Moon',
  'Toxic Moon',
  'Poisonous Moon',
  'Noxious Moon',
  'Corrosive Moon',
  'Acidic Moon',
  'Caustic Moon',
  'Acrid Moon',
  'Blighted Moon',
  'Miasmatic Moon',
  'Rotting Moon',
  'Barren Moon',
  'Desert Moon',
  'Rocky Moon',
  'Bleak Moon',
  'Parched Moon',
  'Abandoned Moon',
  'Dusty Moon',
  'Desolate Moon',
  'Wind-swept Moon',
  'Marshy Moon',
  'Swamp Moon',
  'Tropical Moon',
  'Foggy Moon',
  'Misty Moon',
  'Boggy Moon',
  'Quagmire Moon',
  'Hazy Moon',
  'Cloudy Moon',
  'Vapour Moon',
  'Reeking Moon',
  'Murky Moon',
  'Damp Moon',
  'Endless Morass',
  'Lava Moon',
  'Magma Moon',
  'Erupting Moon',
  'Volcanic Moon',
  'Ash-Shrouded Moon',
  'Ashen Moon',
  'Tectonic Moon',
  'Unstable Moon',
  'Violent Moon',
  'Molten Moon',
  'Flame-Ruptured Moon',
  'Basalt Moon',
  'Imminent Core Detonation',
  'Obsidian Bead',
  'Lost Red Moon',
  'Chromatic Fog Moon',
  'Scarlet Moon',
  'Blood Moon',
  'Wine Dark Moon',
  'Lost Green Moon',
  'Doomed Jade Moon',
  'Haunted Emeril Moon',
  'Lost Blue Moon',
  'Azure Moon',
  'Cerulean Moon',
  'Ultramarine Moon',
  'Stellar Corruption Detected',
  'Vermillion Globe',
  'Vile Anomaly',
  'Toxic Anomaly',
  'Deathly Green Anomaly',
  'Harsh Blue Globe',
  'Frozen Anomaly',
  'Drowning Moon',
  'Oceanic Moon',
  'Tidal Moon',
  'Waterlocked Moon',
  'Aquatic Moon',
  'Marine Moon',
  'Waterworld',
  'Endless Seas',
  'Infested Moon',
  'Worm-ridden Moon',
  'Tainted Moon',
  'Mutated Moon',
  'Corrupted Moon',
  'Infested Paradise',
  'Toxic Horror',
  'Boiling Doom',
  'Radioactive Abomination',
  'Icy Abhorrence',
  'Xeno-Colony',
  'Caustic Nightmare',
  'Fiery Dreadworld',
  'Frozen Hell',
  'Infected Dustbowl',
  'The Nest',
  'Terrorsphere',
  'Abandoned Paradise',
  'Overgrown Moon',
  'Overgrown Relic',
  'The Reliquary',
  'Abandoned Moon',
  'Bleached Ruin',
  'Decaying Ruin',
  'Ruined Moon',
  'Scorched Relic',
  'Lost to Fire',
  'Abandoned Crucible',
  'Ruined Moon',
  'Claimed by Decay',
  'Mutating Relic',
  'Abandoned Moon',
  'Icy Ruin',
  'Frozen Relic',
  'Abandoned Moon',
  'Ruined Moon',
  'Ruined Dustbowl',
  'Abandoned Desert',
  'Abandoned Moon',
] as const;

const InSpanishMoon = [
  'Luna muerto',
  'Luna vacío',
  'Luna desolado',
  'Luna sin habitantes',
  'Luna yermo',
  'Luna olvidado',
  'Luna incompatible con la vida',
  'Luna de atmósfera baja',
  'Luna sin aire',
  'Luna de aspecto abandonado',
  'Catástrofe de terraformación',
  'Luna lluvioso',
  'Luna frondoso',
  'Luna tropical',
  'Luna verdusco',
  'Luna herboso',
  'Luna templado',
  'Luna húmedo',
  'Luna abundante en flora',
  'Luna floreciente',
  'Luna abundante',
  'Luna paradisíaco',
  'Luna en pedazos',
  'Luna con fracturas',
  'Luna en fragmentación',
  'Luna con contornos',
  'Luna con cableado',
  'Luna en red',
  'Luna traqueteante',
  'Luna vertebral',
  'Luna de estructura esquelética',
  'Luna de aleta',
  'Luna de cuchilla',
  'Luna con conchas',
  'Luna con hongos',
  'Luna de esporas',
  'Luna con cubierta',
  'Luna de hueso',
  'Luna en petrificación',
  'Luna en calcificación',
  'Luna con fisuras',
  'Luna con brecha',
  'Luna hexagonal',
  'Luna con coraza',
  'Luna en escamación',
  'Luna con mecánica',
  'Luna de metal',
  'Luna con metales',
  'Luna burbujeante',
  'Luna con espuma',
  'Luna espumante',
  'Luna con columnas',
  'Luna en fragmentos',
  'Luna en pilares',
  'Luna de luz',
  'Luna carmesí',
  'Luna disfuncional',
  'Luna con brecha',
  'Luna infectado',
  'Luna [EDITADO]',
  'Luna vidrioso',
  'Luna sediento',
  'Luna condenado',
  'Luna exterminado',
  'Luna temporal',
  'Luna corrompido',
  'Anomalía planetaria',
  'Luna carbonizado',
  'Luna árido',
  'Luna abrasado',
  'Luna caluroso',
  'Luna tórrido',
  'Luna sofocante',
  'Luna de altas temperaturas',
  'Luna caliente',
  'Luna incandescente',
  'Luna hirviente',
  'Luna congelado',
  'Luna escarchado',
  'Luna ártico',
  'Luna glacial',
  'Luna subcero',
  'Luna algente',
  'Luna con escarcha',
  'Luna inclemente',
  'Luna hiemal',
  'Luna septentrional',
  'Luna irradiado',
  'Luna radiactivo',
  'Luna contaminado',
  'Luna nuclear',
  'Luna molecular',
  'Luna nuclear decadente',
  'Luna de intensidad gamma',
  'Luna de alta radiación',
  'Luna bullente',
  'Luna de gran energía',
  'Luna tóxico',
  'Luna venenoso',
  'Luna nocivo',
  'Luna corrosivo',
  'Luna de clima ácido',
  'Luna ardiente',
  'Luna acre',
  'Luna en ruinas',
  'Luna emanante',
  'Luna débil',
  'Luna estéril',
  'Luna desierto',
  'Luna rocoso',
  'Luna inhóspito',
  'Luna reseco',
  'Luna de aspecto abandonado',
  'Luna con mucho polvo',
  'Luna desolado',
  'Luna de vientos salvajes',
  'Luna marismeño',
  'Luna pantanoso',
  'Luna tropical',
  'Luna neblinoso',
  'Luna brumoso',
  'Luna cenagoso',
  'Luna fangoso',
  'Luna borroso',
  'Luna nublado',
  'Luna vaporoso',
  'Luna apestoso',
  'Luna turbio',
  'Luna húmedo',
  'Cenagal infinito',
  'Luna lávico',
  'Luna magmático',
  'Luna en erupción',
  'Luna volcánico',
  'Luna envuelto en ceniza',
  'Luna cenizo',
  'Luna tectónico',
  'Luna inestable',
  'Luna violento',
  'Luna derretido',
  'Luna quebrado por las llamas',
  'Luna basáltico',
  'Detonación del núcleo inminente',
  'Goteo de obsidiana',
  'Luna rojo perdido',
  'Luna niebla cromática',
  'Luna escarlata',
  'Luna sangre',
  'Luna vino tinto',
  'Luna verde perdido',
  'Luna jade maldito',
  'Luna emerilio encantado',
  'Luna azul perdido',
  'Luna azul celeste',
  'Luna azul cerúleo',
  'Luna ultramarino',
  'Corrupción estelar detectada',
  'Globo bermellón',
  'Anomalía malvada',
  'Anomalía tóxica',
  'Anomalía mortal verde',
  'Globo azul chillón',
  'Anomalía helada',
  'Luna ahogado',
  'Luna oceánico',
  'Luna de mareas',
  'Luna anegado',
  'Luna acuático',
  'Luna marino',
  'Mundo acuático',
  'Mares infinito',
  'Luna infestado',
  'Luna infestado de gusanos',
  'Luna contaminado',
  'Luna mutado',
  'Luna corrompido',
  'Paraíso infestado',
  'Horror tóxico',
  'Destrucción hirviente',
  'Abominación radioactiva',
  'Aberración gélida',
  'Xenocolonia',
  'Pesadilla cáustica',
  'Mundo terrorífico fogoso',
  'Infierno congelado',
  'Tierra desértica infectada',
  'El nido',
  'Terrorfera',
  'Paraíso abandonado',
  'Luna abundante en flora',
  'Reliquia consumida por la espesura',
  'El relicario',
  'Luna de aspecto abandonado',
  'Ruina blanqueada',
  'Ruina en declive',
  'Luna en ruinas',
  'Reliquia abrasada',
  'Perdido por el fuego',
  'Crisol abandonado',
  'Luna en ruinas',
  'Consumido por el deterioro',
  'Reliquia mutante',
  'Luna de aspecto abandonado',
  'Ruina helada',
  'Reliquia congelada',
  'Luna de aspecto abandonado',
  'Luna arruinado',
  'Polvareda en ruinas',
  'Desierto abandonado',
  'Luna de aspecto abandonado',
] as const;

const InEnglishGiant = [
  'Dead Giant',
  'Empty Giant',
  'Desolate Giant',
  'Lifeless Giant',
  'Forsaken Giant',
  'Life-Incompatible Giant',
  'Low Atmosphere Giant',
  'Airless Giant',
  'Abandoned Giant',
  'Terraforming Catastrophe',
  'Rainy Giant',
  'Verdant Giant',
  'Tropical Giant',
  'Viridescent Giant',
  'Grassy Giant',
  'Temperate Giant',
  'Humid Giant',
  'Overgrown Giant',
  'Flourishing Giant',
  'Bountiful Giant',
  'Paradise Giant',
  'Shattered Giant',
  'Fractured Giant',
  'Fragmented Giant',
  'Contoured Giant',
  'Cabled Giant',
  'Webbed Giant',
  'Rattling Giant',
  'Spined Giant',
  'Skeletal Giant',
  'Finned Giant',
  'Bladed Giant',
  'Shell-Strewn Giant',
  'Fungal Giant',
  'Sporal Giant',
  'Capped Giant',
  'Ossified Giant',
  'Petrified Giant',
  'Calcified Giant',
  'Fissured Giant',
  'Breached Giant',
  'Hexagonal Giant',
  'Plated Giant',
  'Scaly Giant',
  'Mechanical Giant',
  'Metallic Giant',
  'Metallurgic Giant',
  'Bubbling Giant',
  'Frothing Giant',
  'Foaming Giant',
  'Columned Giant',
  'Sharded Giant',
  'Pillared Giant',
  'Giant of Light',
  'Crimson Giant',
  'Malfunctioning Giant',
  'Breached Giant',
  'Infected Giant',
  '[REDACTED] Giant',
  'Glassy Giant',
  'Thirsty Giant',
  'Doomed Giant',
  'Erased Giant',
  'Temporary Giant',
  'Corrupted Giant',
  'Planetary Anomaly',
  'Charred Giant',
  'Arid Giant',
  'Scorched Giant',
  'Hot Giant',
  'Fiery Giant',
  'Boiling Giant',
  'High Temperature Giant',
  'Torrid Giant',
  'Incandescent Giant',
  'Scalding Giant',
  'Frozen Giant',
  'Icebound Giant',
  'Arctic Giant',
  'Glacial Giant',
  'Sub-zero Giant',
  'Icy Giant',
  'Frostbound Giant',
  'Freezing Giant',
  'Hiemal Giant',
  'Hyperborean Giant',
  'Irradiated Giant',
  'Radioactive Giant',
  'Contaminated Giant',
  'Nuclear Giant',
  'Isotopic Giant',
  'Decaying Nuclear Giant',
  'Gamma-Intensive Giant',
  'High Radio Source Giant',
  'Supercritical Giant',
  'High Energy Giant',
  'Toxic Giant',
  'Poisonous Giant',
  'Noxious Giant',
  'Corrosive Giant',
  'Acidic Giant',
  'Caustic Giant',
  'Acrid Giant',
  'Blighted Giant',
  'Miasmatic Giant',
  'Rotting Giant',
  'Barren Giant',
  'Desert Giant',
  'Rocky Giant',
  'Bleak Giant',
  'Parched Giant',
  'Abandoned Giant',
  'Dusty Giant',
  'Desolate Giant',
  'Wind-swept Giant',
  'Marshy Giant',
  'Swamp Giant',
  'Tropical Giant',
  'Foggy Giant',
  'Misty Giant',
  'Boggy Giant',
  'Quagmire Giant',
  'Hazy Giant',
  'Cloudy Giant',
  'Vapour Giant',
  'Reeking Giant',
  'Murky Giant',
  'Damp Giant',
  'Endless Morass',
  'Lava Giant',
  'Magma Giant',
  'Erupting Giant',
  'Volcanic Giant',
  'Ash-Shrouded Giant',
  'Ashen Giant',
  'Tectonic Giant',
  'Unstable Giant',
  'Violent Giant',
  'Molten Giant',
  'Flame-Ruptured Giant',
  'Basalt Giant',
  'Imminent Core Detonation',
  'Obsidian Bead',
  'Lost Red Giant',
  'Chromatic Fog Giant',
  'Scarlet Giant',
  'Blood Giant',
  'Wine Dark Giant',
  'Lost Green Giant',
  'Doomed Jade Giant',
  'Haunted Emeril Giant',
  'Lost Blue Giant',
  'Azure Giant',
  'Cerulean Giant',
  'Ultramarine Giant',
  'Stellar Corruption Detected',
  'Vermillion Globe',
  'Vile Anomaly',
  'Toxic Anomaly',
  'Deathly Green Anomaly',
  'Harsh Blue Globe',
  'Frozen Anomaly',
  'Drowning Giant',
  'Oceanic Giant',
  'Tidal Giant',
  'Waterlocked Giant',
  'Aquatic Giant',
  'Marine Giant',
  'Waterworld',
  'Endless Seas',
  'Infested Giant',
  'Worm-ridden Giant',
  'Tainted Giant',
  'Mutated Giant',
  'Corrupted Giant',
  'Infested Paradise',
  'Toxic Horror',
  'Boiling Doom',
  'Radioactive Abomination',
  'Icy Abhorrence',
  'Xeno-Colony',
  'Caustic Nightmare',
  'Fiery Dreadworld',
  'Frozen Hell',
  'Infected Dustbowl',
  'The Nest',
  'Terrorsphere',
  'Abandoned Paradise',
  'Overgrown Gigant',
  'Overgrown Relic',
  'The Reliquary',
  'Abandoned Gigant',
  'Bleached Ruin',
  'Decaying Ruin',
  'Ruined Gigant',
  'Scorched Relic',
  'Lost to Fire',
  'Abandoned Crucible',
  'Ruined Gigant',
  'Claimed by Decay',
  'Mutating Relic',
  'Abandoned Gigant',
  'Icy Ruin',
  'Frozen Relic',
  'Abandoned Gigant',
  'Ruined Gigant',
  'Ruined Dustbowl',
  'Abandoned Desert',
  'Abandoned Gigant',
] as const;

const InSpanishGiant = [
  'Gigante muerto',
  'Gigante vacío',
  'Gigante desolado',
  'Gigante sin habitantes',
  'Gigante yermo',
  'Gigante olvidado',
  'Gigante incompatible con la vida',
  'Gigante de atmósfera baja',
  'Gigante sin aire',
  'Gigante de aspecto abandonado',
  'Catástrofe de terraformación',
  'Gigante lluvioso',
  'Gigante frondoso',
  'Gigante tropical',
  'Gigante verdusco',
  'Gigante herboso',
  'Gigante templado',
  'Gigante húmedo',
  'Gigante abundante en flora',
  'Gigante floreciente',
  'Gigante abundante',
  'Gigante paradisíaco',
  'Gigante en pedazos',
  'Gigante con fracturas',
  'Gigante en fragmentación',
  'Gigante con contornos',
  'Gigante con cableado',
  'Gigante en red',
  'Gigante traqueteante',
  'Gigante vertebral',
  'Gigante de estructura esquelética',
  'Gigante de aleta',
  'Gigante de cuchilla',
  'Gigante con conchas',
  'Gigante con hongos',
  'Gigante de esporas',
  'Gigante con cubierta',
  'Gigante de hueso',
  'Gigante en petrificación',
  'Gigante en calcificación',
  'Gigante con fisuras',
  'Gigante con brecha',
  'Gigante hexagonal',
  'Gigante con coraza',
  'Gigante en escamación',
  'Gigante con mecánica',
  'Gigante de metal',
  'Gigante con metales',
  'Gigante burbujeante',
  'Gigante con espuma',
  'Gigante espumante',
  'Gigante con columnas',
  'Gigante en fragmentos',
  'Gigante en pilares',
  'Gigante de luz',
  'Gigante carmesí',
  'Gigante disfuncional',
  'Gigante con brecha',
  'Gigante infectado',
  'Gigante [EDITADO]',
  'Gigante vidrioso',
  'Gigante sediento',
  'Gigante condenado',
  'Gigante exterminado',
  'Gigante temporal',
  'Gigante corrompido',
  'Anomalía planetaria',
  'Gigante carbonizado',
  'Gigante árido',
  'Gigante abrasado',
  'Gigante caluroso',
  'Gigante tórrido',
  'Gigante sofocante',
  'Gigante de altas temperaturas',
  'Gigante caliente',
  'Gigante incandescente',
  'Gigante hirviente',
  'Gigante congelado',
  'Gigante escarchado',
  'Gigante ártico',
  'Gigante glacial',
  'Gigante subcero',
  'Gigante algente',
  'Gigante con escarcha',
  'Gigante inclemente',
  'Gigante hiemal',
  'Gigante septentrional',
  'Gigante irradiado',
  'Gigante radiactivo',
  'Gigante contaminado',
  'Gigante nuclear',
  'Gigante molecular',
  'Gigante nuclear decadente',
  'Gigante de intensidad gamma',
  'Gigante de alta radiación',
  'Gigante bullente',
  'Gigante de gran energía',
  'Gigante tóxico',
  'Gigante venenoso',
  'Gigante nocivo',
  'Gigante corrosivo',
  'Gigante de clima ácido',
  'Gigante ardiente',
  'Gigante acre',
  'Gigante en ruinas',
  'Gigante emanante',
  'Gigante débil',
  'Gigante estéril',
  'Gigante desierto',
  'Gigante rocoso',
  'Gigante inhóspito',
  'Gigante reseco',
  'Gigante de aspecto abandonado',
  'Gigante con mucho polvo',
  'Gigante desolado',
  'Gigante de vientos salvajes',
  'Gigante marismeño',
  'Gigante pantanoso',
  'Gigante tropical',
  'Gigante neblinoso',
  'Gigante brumoso',
  'Gigante cenagoso',
  'Gigante fangoso',
  'Gigante borroso',
  'Gigante nublado',
  'Gigante vaporoso',
  'Gigante apestoso',
  'Gigante turbio',
  'Gigante húmedo',
  'Cenagal infinito',
  'Gigante lávico',
  'Gigante magmático',
  'Gigante en erupción',
  'Gigante volcánico',
  'Gigante envuelto en ceniza',
  'Gigante cenizo',
  'Gigante tectónico',
  'Gigante inestable',
  'Gigante violento',
  'Gigante derretido',
  'Gigante quebrado por las llamas',
  'Gigante basáltico',
  'Detonación del núcleo inminente',
  'Goteo de obsidiana',
  'Gigante rojo perdido',
  'Gigante niebla cromática',
  'Gigante escarlata',
  'Gigante sangre',
  'Gigante vino tinto',
  'Gigante verde perdido',
  'Gigante jade maldito',
  'Gigante emerilio encantado',
  'Gigante azul perdido',
  'Gigante azul celeste',
  'Gigante azul cerúleo',
  'Gigante ultramarino',
  'Corrupción estelar detectada',
  'Globo bermellón',
  'Anomalía malvada',
  'Anomalía tóxica',
  'Anomalía mortal verde',
  'Globo azul chillón',
  'Anomalía helada',
  'Gigante ahogado',
  'Gigante oceánico',
  'Gigante de mareas',
  'Gigante anegado',
  'Gigante acuático',
  'Gigante marino',
  'Mundo acuático',
  'Mares infinito',
  'Gigante infestado',
  'Gigante infestado de gusanos',
  'Gigante contaminado',
  'Gigante mutado',
  'Gigante corrompido',
  'Paraíso infestado',
  'Horror tóxico',
  'Destrucción hirviente',
  'Abominación radioactiva',
  'Aberración gélida',
  'Xenocolonia',
  'Pesadilla cáustica',
  'Mundo terrorífico fogoso',
  'Infierno congelado',
  'Tierra desértica infectada',
  'El nido',
  'Terrorfera',
  'Paraíso abandonado',
  'Gigante abundante en flora',
  'Reliquia consumida por la espesura',
  'El relicario',
  'Gigante de aspecto abandonado',
  'Ruina blanqueada',
  'Ruina en declive',
  'Gigante en ruinas',
  'Reliquia abrasada',
  'Perdido por el fuego',
  'Crisol abandonado',
  'Gigante en ruinas',
  'Consumido por el deterioro',
  'Reliquia mutante',
  'Gigante de aspecto abandonado',
  'Ruina helada',
  'Reliquia congelada',
  'Gigante de aspecto abandonado',
  'Gigante arruinado',
  'Polvareda en ruinas',
  'Desierto abandonado',
  'Gigante de aspecto abandonado',
] as const;

export const mappedMoonDescriptors: SelectOption[] = InSpanishMoon.map((mode, index) => ({
  label: mode,
  value: InEnglishMoon[index],
}));

export const mappedGiantDescriptors: SelectOption[] = InSpanishGiant.map((mode, index) => ({
  label: mode,
  value: InEnglishGiant[index],
}));
