import type { SelectOption } from '@/types/selectInputOptions';

export const PlanetWeather: readonly (readonly [string, string])[] = [
  ['Tropical Storms', 'Tormentas tropicales'],
  ['Occasional Boiling Fog', 'Bruma hirviente ocasional'],
  ['Superheated Mists', 'Neblina sobrecalentada'],
  ['Painful Mist', 'Bruma dolorosa'],
  ['Infrequent Torrents', 'Torrentes poco frecuentes'],
  ['Oppressive', 'Opresivo'],
  ['Soggy Danger', 'Peligro empapado'],
  ['Sticky Heat', 'Calor pegajoso'],
  ['Clammy Menace', 'Amenaza sudada'],
  ['Hazardous Moisture', 'Peligro humectado'],
  ['Gentle Mist', 'Bruma suave'],
  ['Humid', 'Húmedo'],
  ['Tropical Winds', 'Vientos tropicales'],
  ['Warm Fog', 'Niebla cálida'],
  ['Temperate Murk', 'Neblina moderada'],
  ['Mild Damp', 'Llovizna suave'],
  ['Warm Dewdrops', 'Gotas de rocío calientes'],
  ['Tepid Damp', 'Vaho tibio'],
  ['Sweaty Drizzle', 'Llovizna sudorosa'],
  ['Muggy Haze', 'Neblina húmeda'],
  ['Death Fog', 'Niebla mortal'],
  ['Sultry Disaster', 'Desastre sofocante'],
  ['Cataclysmic Monsoons', 'Monzones catastróficos'],
  ['Mists of Annihilation', 'Neblina de aniquilación'],
  ['All-Consuming Fog', 'Niebla absorbente'],
  ['Liquid Hell', 'Infierno líquido'],
  ['Storms of Desolation', 'Tormentas desoladoras'],
  ['Melting Deluges', 'Diluvios de fundición'],
  ['Boiling Catastrophe', 'Catástrofe hirviente'],
  ['Damp Misery', 'Miseria pegajosa'],
  ['Heated Gas Pockets', 'Bolsas de gas calientes'],
  ['Occasional Firestorms', 'Tormentas de fuego ocasionales'],
  ['Incendiary Winds', 'Vientos incendiarios'],
  ['Unpredictable Conflagrations', 'Conflagraciones impredecibles'],
  ['Drifting Firestorms', 'Tormentas de fuego a la deriva'],
  ['Pillars of Flame', 'Pilares de llamas'],
  ['Magma Geysers', 'Géiseres de magma'],
  ['Plumes of Fire', 'Columnas de fuego'],
  ['Molten Rain', 'Lluvia de lava'],
  ['Tectonic Storms', 'Tormentas tectónicas'],
  ['Smothering Ash', 'Ceniza irrespirable'],
  ['Sulphurous Haze', 'Neblina sulfurosa'],
  ['Ash Wisps', 'Volutas de ceniza'],
  ['Drifting Smog', 'Niebla tóxica a la deriva'],
  ['Cinderfalls', 'Carbonilla'],
  ['Ash Plumes', 'Columnas de ceniza'],
  ['Choking Ash', 'Ceniza asfixiante'],
  ['Burning Mists', 'Neblinas abrasadoras'],
  ['Sulfur Fumes', 'Gases sulfurosos'],
  ['Enveloping Ash', 'Ceniza envolvente'],
  ['Ashen Winds', 'Vientos cenizos'],
  ['Frequent Firestorms', 'Tormentas de fuego frecuentes'],
  ['Walls of Flame', 'Paredes de llamas'],
  ['Clouds of Fire', 'Nubes de fuego'],
  ['Ashen Destruction', 'Destrucción cenizosa'],
  ['Magma Rain', 'Lluvia de magma'],
  ['Basalt Hail', 'Granizo basáltico'],
  ['Explosive Gas Eruptions', 'Erupciones explosivas de gas'],
  ['Lethal Ash Storms', 'Tormentas de ceniza letales'],
  ['Sulphurous Inferno', 'Infierno sulfuroso'],
  ['Colossal Firestorms', 'Tormentas de fuego colosales'],
  ['Obsidian Doom', 'Catástrofe de obsidiana'],
  ['Gas Storms', 'Tormentas de gas'],
  ['Eternal Cyclones', 'Ciclones eternos'],
  ['Planet-Wide Maelstrom', 'Vorágine planetaria'],
  ['Constant Pressure Storms', 'Tormentas de presión constante'],
  ['Infrequent Heat Storms', 'Tormentas de calor inusuales'],
  ['Rare Firestorms', 'Lluvias de fuego raras'],
  ['Superheated Gas Pockets', 'Bolsas de gas supercalientes'],
  ['Wandering Hot Spots', 'Zonas calientes ambulantes'],
  ['Atmospheric Heat Instabilities', 'Inestabilidades de calor'],
  ['Direct Sunlight', 'Exposición directa al sol'],
  ['Heated Atmosphere', 'Atmósfera ardiente'],
  ['Occasional Ash Storms', 'Lluvias de ceniza ocasionales'],
  ['Dangerously Hot', 'Peligrosamente caliente'],
  ['Burning Air', 'Aire abrasador'],
  ['Parched', 'Reseco'],
  ['Overly Warm', 'Excesivamente cálido'],
  ['Sunny', 'Soleado'],
  ['Dehydrated', 'Deshidratado'],
  ['Unending Sunlight', 'Luz solar infinita'],
  ['Sweltering', 'Caldeado'],
  ['Extreme Heat', 'Calor extremo'],
  ['Burning Gas Clouds', 'Nubes de gas ardiente'],
  ['Intense Heat', 'Calor intenso'],
  ['Superheated Air', 'Aire sobrecalentado'],
  ['Scalding Heat', 'Calor escaldado'],
  ['Inferno Winds', 'Vientos infernales'],
  ['Firestorms', 'Lluvias de fuego'],
  ['Combustible Dust', 'Polvo combustible'],
  ['Incendiary Dust', 'Polvo incendiario'],
  ['Self-Igniting Storms', 'Tormentas autoinflamables'],
  ['Howling Blizzards', 'Ventiscas huracanadas'],
  ['Intense Cold', 'Frío intenso'],
  ['Icy Tempests', 'Tempestad gélida'],
  ['Supercooled Storms', 'Tormentas sobreenfriadas'],
  ['Raging Snowstorms', 'Tormentas de nieve violentas'],
  ['Ice Storms', 'Tormentas de hielo'],
  ['Deep Freeze', 'Congelante'],
  ['Roaring Ice Storms', 'Tormentas de hielo violentas'],
  ['Frequent Blizzards', 'Ventiscas frecuentes'],
  ['Hazardous Whiteouts', 'Heladas peligrosas'],
  ['Frozen Clouds', 'Nubes congeladas'],
  ['Occasional Snowfall', 'Nevadas ocasionales'],
  ['Infrequent Blizzards', 'Ventiscas poco frecuentes'],
  ['Outbreaks of Frozen Rain', 'Estallidos de lluvia gélida'],
  ['Harsh, Icy Winds', 'Vientos gélidos fuertes'],
  ['Drifting Snowstorms', 'Tormentas de nieve errantes'],
  ['Migratory Blizzards', 'Ventiscas migratorias'],
  ['Icy Blasts', 'Ráfagas de hielo'],
  ['Wandering Frosts', 'Escarchas errantes'],
  ['Powder Snow', 'Nieve polvo'],
  ['Wintry', 'Invernal'],
  ['Snowy', 'Nevoso'],
  ['Icy', 'Gélido'],
  ['Crisp', 'Vigorizante'],
  ['Frost', 'Escarcha'],
  ['Freezing', 'Congelante'],
  ['Permafrost', 'Eternamente congelado'],
  ['Frequent Toxic Floods', 'Riadas tóxicas frecuentes'],
  ['Toxic Superstorms', 'Supertormentas tóxicas'],
  ['Acidic Deluges', 'Diluvios ácidos'],
  ['Corrosive Cyclones', 'Ciclones corrosivos'],
  ['Caustic Floods', 'Inundaciones cáusticas'],
  ['Corrosive Storms', 'Tormentas corrosivas'],
  ['Torrential Acid', 'Ácido torrencial'],
  ['Noxious Gas Storms', 'Tormentas de gas nocivo'],
  ['Toxic Monsoons', 'Monzones tóxicos'],
  ['Bone-Stripping Acid Storms', 'Tormentas ácidas dolorosas'],
  ['Corrosive Rainstorms', 'Tempestades corrosivas'],
  ['Pouring Toxic Rain', 'Lluvia tóxica torrencial'],
  ['Occasional Acid Storms', 'Tormentas ácidas ocasionales'],
  ['Atmospheric Corruption', 'Corrupción atmosférica'],
  ['Poison Flurries', 'Chaparrones venenosos'],
  ['Toxic Outbreaks', 'Estallidos tóxicos'],
  ['Acidic Dust Pockets', 'Bolsas de polvo ácido'],
  ['Passing Toxic Fronts', 'Frentes tóxicos superficiales'],
  ['Caustic Winds', 'Vientos cáusticos'],
  ['Alkaline Cloudbursts', 'Chaparrones alcalinos'],
  ['Dangerously Toxic Rain', 'Lluvia peligrosamente tóxica'],
  ['Corrosive Sleet Storms', 'Tormentas corrosivas'],
  ['Lethal Atmosphere', 'Atmósfera letal'],
  ['Infrequent Toxic Drizzle', 'Lloviznas tóxicas inusuales'],
  ['Acid Rain', 'Lluvia ácida'],
  ['Toxic Clouds', 'Nubes tóxicas'],
  ['Poison Rain', 'Lluvia venenosa'],
  ['Choking Clouds', 'Nubes asfixiantes'],
  ['Caustic Moisture', 'Humedad cáustica'],
  ['Poisonous Gas', 'Gas venenoso'],
  ['Stinging Atmosphere', 'Atmósfera urticante'],
  ['Toxic Damp', 'Vaho tóxico'],
  ['Corrosive Damp', 'Vaho corrosivo'],
  ['Stinging Puddles', 'Charcos urticantes'],
  ['Extreme Radioactivity', 'Radiactividad extrema'],
  ['Irradiated Thunderstorms', 'Tormentas irradiadas'],
  ['Planet-Wide Radiation Storms', 'Tormentas radiactivas'],
  ['Extreme Atmospheric Decay', 'Atmósfera en desintegración'],
  ['Roaring Nuclear Wind', 'Viento nuclear violento'],
  ['Gamma Cyclones', 'Ciclones gamma'],
  ['Contaminated Squalls', 'Chubascos contaminados'],
  ['Extreme Thermonuclear Fog', 'Niebla termonuclear extrema'],
  ['Frequent Particle Eruptions', 'Partículas en erupción'],
  ['Enormous Nuclear Storms', 'Tormentas nucleares enormes'],
  ['Particulate Winds', 'Vientos de partículas'],
  ['Energetic Storms', 'Tormentas energéticas'],
  ['Irradiated Downpours', 'Diluvios irradiados'],
  ['Radioactive Dust Storms', 'Tormentas de polvo radiactivo'],
  ['Volatile Windstorms', 'Vendaval volátil'],
  ['Occasional Radiation Outbursts', 'Descargas radiactivas casuales'],
  ['Irradiated Storms', 'Tormentas irradiadas'],
  ['Unstable Fog', 'Niebla inestable'],
  ['Reactive Rain', 'Lluvia reactiva'],
  ['Radioactive Humidity', 'Humedad radiactiva'],
  ['Radioactive Damp', 'Vaho radiactivo'],
  ['Irradiated Winds', 'Vientos irradiados'],
  ['Contaminated Puddles', 'Charcos contaminados'],
  ['Volatile Winds', 'Vientos volátiles'],
  ['Unstable Atmosphere', 'Atmósfera inestable'],
  ['Gamma Dust', 'Polvo gamma'],
  ['Nuclidic Atmosphere', 'Atmósfera nucléidica'],
  ['Boiling Superstorms', 'Supertormentas asfixiantes'],
  ['Intense Heatbursts', 'Estallidos de calor intenso'],
  ['Superheated Rain', 'Lluvia sobrecalentada'],
  ['Boiling Monsoons', 'Monzones asfixiantes'],
  ['Broiling Humidity', 'Humedad achicharrante'],
  ['Painfully Hot Rain', 'Lluvia abrasadora'],
  ['Torrential Heat', 'Calor torrencial'],
  ['Blistering Floods', 'Inundaciones abrasadoras'],
  ['Scalding Rainstorms', 'Temporales abrasadores'],
  ['Torrid Deluges', 'Diluvios tórridos'],
  ['Boiling Puddles', 'Charcos asfixiantes'],
  ['Sweltering Damp', 'Vaho caldeado'],
  ['Superheated Drizzle', 'Llovizna sobrecalentada'],
  ['Dangerously Hot Fog', 'Peligrosa niebla caliente'],
  ['Choking Humidity', 'Humedad asfixiante'],
  ['Mostly Calm', 'En su mayoría calmado'],
  ['Occasional Scalding Cloudbursts', 'Lluvia abrasadora ocasional'],
  ['Usually Mild', 'Normalmente apacible'],
  ['Blistering Damp', 'Vaho abrasador'],
  ['Lethal Humidity Outbreaks', 'Estallidos de humedad letal'],
  ['Temperate', 'Moderado'],
  ['Light Showers', 'Lluvias leves'],
  ['Mild Rain', 'Llovizna'],
  ['Refreshing Breeze', 'Brisa refrescante'],
  ['Pleasant', 'Agradable'],
  ['Balmy', 'Sereno'],
  ['Mellow', 'Apacible'],
  ['Beautiful', 'Precioso'],
  ['Blissful', 'Maravilloso'],
  ['Billowing Dust Storms', 'Tormentas de polvo ondulante'],
  ['Choking Sandstorms', 'Tormentas de arena opresivas'],
  ['Hazardous Temperature Extremes', 'Hazardous Temperature Extremes'],
  ['Lung-Burning Night Wind', 'Temp. extremas peligrosas'],
  ['Extreme Wind Blasting', 'Ráfagas de viento extremo'],
  ['Planetwide Desiccation', 'Desecación planetaria'],
  ['Sand Blizzards', 'Ventiscas de arena'],
  ['Howling Gales', 'Vendaval huracanado'],
  ['Dead Wastes', 'Páramos muertos'],
  ['Occasional Sandstorms', 'Tormentas de arena casuales'],
  ['Infrequent Dust Storms', 'Tormentas de polvo inusuales'],
  ['Intermittent Wind Blasting', 'Ráfagas de viento casuales'],
  ['Parched Sands', 'Arenas resecas'],
  ['Sporadic Grit Storms', 'Tormentas de arena fortuitas'],
  ['Dust-Choked Winds', 'Vientos de polvo asfixiantes'],
  ['Highly Variable Temperatures', 'Temperaturas muy variables'],
  ['Blasted Atmosphere', 'Atmósfera arruinada'],
  ['Freezing Night Winds', 'Vientos nocturnos gélidos'],
  ['Ceaseless Drought', 'Sequía incesante'],
  ['Moistureless', 'Desaguado'],
  ['Baked', 'Reseco'],
  ['Sterile', 'Estéril'],
  ['Unclouded Skies', 'Cielos despejados'],
  ['Dry Gusts', 'Ráfagas secas'],
  ['Withered', 'Mustio'],
  ['Icy Nights', 'Noches heladas'],
  ['Perfectly Clear', 'Totalmente despejado'],
  ['Absent', 'Ausente'],
  ['No Atmosphere', 'Sin atmósfera'],
  ['Utterly Still', 'Totalmente calmado'],
  ['Peaceful', 'Pacífico'],
  ['Eerily Calm', 'Misteriosamente calmado'],
  ['Airless', 'Sin viento'],
  ['Silent', 'Silencioso'],
  ['Inert', 'Inerte'],
  ['Clear', 'Despejado'],
  ['Fair', 'Favorable'],
  ['Fine', 'Suave'],
  ['Moderate', 'Moderado'],
  ['Peaceful Climate', 'Buen clima'],
  ['Tempered', 'Templado'],
  ['Emollient', 'Tranquilo'],
  ['Invisible Mist', 'Niebla invisible'],
  ['Internal Rain', 'Lluvia interna'],
  ['Lost Clouds', 'Nubes perdidas'],
  ['Crimson Heat', 'Calor carmesí'],
  ['Winds of Glass', 'Vientos vidriosos'],
  ['Thirsty Clouds', 'Nubes sedientas'],
  ['Obsidian Heat', 'Calor de obsidiana'],
  ['Memories of Frost', 'Recuerdos de escarcha'],
  ['Haunted Frost', 'Escarcha angustiosa'],
  ['Indetectable Burning', 'Fuego indetectable'],
  ['[REDACTED]', '[EDITADO]'],
  ['Anomalous', 'Anómalo'],
  ['Burning Crimson', 'Carmesí abrasador'],
  ['Scarlet Rain', 'Lluvia escarlata'],
  ['Fevered Clouds', 'Nubes agitadas'],
  ['Carmine Winds', 'Vientos de carmín'],
  ['Red Mist', 'Neblina roja'],
  ['Flaming Hail', 'Granizo llameante'],
  ['Vermillion Storms', 'Tormentas bermellonas'],
  ['Rain of Atlas', 'Lluvia del Atlas'],
  ['Angered Clouds', 'Nubes enfurecidas'],
  ['Blood Rain', 'Lluvia de sangre'],
  ['Bilious Storms', 'Tormentas biliosas'],
  ['Deadly Pressure Variations', 'Variaciones de presión mortales'],
  ['Harsh Toxic Wind', 'Viento tóxico fuerte'],
  ['Corrupted Blood', 'Sangre corrompida'],
  ['Infinite Toxic Mist', 'Neblina tóxica infinita'],
  ['Echoes of Acid', 'Ecos de ácido'],
  ['Poison Cyclones', 'Ciclones venenosos'],
  ['Inescapable Toxins', 'Toxinas inevitables'],
  ['Clouds of Haunted Green', 'Nubes de verde encantado'],
  ['Invisible Jade Winds', 'Vientos de jade invisibles'],
  ['Frozen Mists', 'Neblinas congeladas'],
  ['Electric Rain', 'Lluvia eléctrica'],
  ['Azure Storms', 'Tormentas de azul celeste'],
  ['Extreme Low Pressure', 'Presión extremadamente baja'],
  ['All-Consuming Cold', 'Frío absorbente'],
  ['Winds from Beyond', 'Vientos del más allá'],
  ['Unfathomable Storms', 'Tormentas insondables'],
  ['Unimaginable Blue', 'Azul inimaginable'],
  ['Ultramarine Wind', 'Viento azul ultramarino'],
  ['Inverted Superstorms', 'Supertormentas invertidas'],
  ['Coastal Storms', 'Tormentas costeras'],
] as const;

export const mappedPlanetWeather: SelectOption[] = PlanetWeather.map(([value, label]) => ({
  label,
  value,
}));
