import type { SelectOption } from '@/types/selectInputOptions';

export const SystemTradeables: readonly (readonly [string, string])[] = [
  ['Star Silk', 'Seda estelar'],
  ['Comet Droplets', 'Gotas de cometa'],
  ['Ion Sphere', 'Esfera de iones'],
  ['Decrypted User Data', 'Datos de usuario desencriptados'],
  ['Teleport Coordinators', 'Coordinadores de teletransporte'],
  ['Nanotube Crate', 'Caja de nanotubos'],
  ['Self-Repairing Heridium', 'Heridio autorreparable'],
  ['Optical Solvent', 'Disolvente óptico'],
  ['5D Torus', 'Toro 5D'],
  ['Superconducting Fibre', 'Fibra superconductora'],
  ['De-Scented Bottles', 'Botellas sin aroma'],
  ['Neutron Microscope', 'Microscopio de neutrones'],
  ['Instability Injector', 'Inyector de inestabilidad'],
  ['Organic Piping', 'Canalización orgánica'],
  ['Neural Duct', 'Conducto neuronal'],
  ['Dirt', 'Suciedad'],
  ['Unrefined Pyrite Grease', 'Grasa de pirita sin refinar'],
  ['Bromide Salt', 'Sal de bromuro'],
  ['Polychromatic Zirconium', 'Circonio policromo'],
  ['Re-latticed Arc Crystal', 'Cristal de doble arco reticular'],
  ['Enormous Metal Cog', 'Diente metálico enorme'],
  ['Non-Stick Piston', 'Pistón antiadherente'],
  ['Mesh Decouplers', 'Desacopladores de malla'],
  ['Holographic Crankshaft', 'Cigüeñal holográfico'],
  ['Vector Compressors', 'Compresores vectoriales'],
  ['Decommissioned Circuits', 'Circuitos desguazados'],
  ['Welding Soap', 'Tiza para soldadura'],
  ['Ion Capacitor', 'Condensador de iones'],
  ['Autonomous Positioning Unit', 'Unidad de posicionamiento autónoma'],
  ['Quantum Accelerator', 'Acelerador de cuantos'],
  ['Spark Canister', 'Bote de chispas'],
  ['Industrial-Grade Battery', 'Batería industrial'],
  ['Ohmic Gel', 'Gel óhmico'],
  ['Experimental Power Fluid', 'Fluido de energía experimental'],
  ['Fusion Core', 'Núcleo de fusión'],
] as const;

export const mappedSystemTradeables: SelectOption[] = SystemTradeables.map(([value, label]) => ({
  label,
  value,
}));
