allowBuilds:
  '@parcel/watcher': true
  edgedriver: true
  geckodriver: true
  tesseract.js: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.1'
  - '@vitest/browser@4.1.7'
  - '@vitest/coverage-v8@4.1.7'
  - '@vitest/expect@4.1.7'
  - '@vitest/mocker@4.1.7'
  - '@vitest/pretty-format@4.1.7'
  - '@vitest/runner@4.1.7'
  - '@vitest/snapshot@4.1.7'
  - '@vitest/spy@4.1.7'
  - '@vitest/utils@4.1.7'
  - stylelint@17.12.0
  - vitest@4.1.7
  - sass-embedded-all-unknown@1.100.0
  - sass-embedded-android-arm64@1.100.0
  - sass-embedded-android-arm@1.100.0
  - sass-embedded-android-riscv64@1.100.0
  - sass-embedded-android-x64@1.100.0
  - sass-embedded-darwin-arm64@1.100.0
  - sass-embedded-darwin-x64@1.100.0
  - sass-embedded-linux-arm64@1.100.0
  - sass-embedded-linux-arm@1.100.0
  - sass-embedded-linux-musl-arm64@1.100.0
  - sass-embedded-linux-musl-arm@1.100.0
  - sass-embedded-linux-musl-riscv64@1.100.0
  - sass-embedded-linux-musl-x64@1.100.0
  - sass-embedded-linux-riscv64@1.100.0
  - sass-embedded-linux-x64@1.100.0
  - sass-embedded-unknown-all@1.100.0
  - sass-embedded-win32-arm64@1.100.0
  - sass-embedded-win32-x64@1.100.0
  - sass-embedded@1.100.0
  - sass@1.100.0
